export const timezones = [
  {
    name: "Pacific/Midway",
    offset: -660,
    city: "Midway",
    region: "Pacific",
    offsetStr: "GMT+11:00",
  },
  {
    name: "Pacific/Niue",
    offset: -660,
    city: "Niue",
    region: "Pacific",
    offsetStr: "GMT+11:00",
  },
  {
    name: "Pacific/Pago_Pago",
    offset: -660,
    city: "Pago Pago",
    region: "Pacific",
    offsetStr: "GMT+11:00",
  },
  {
    name: "Pacific/Samoa",
    offset: -660,
    city: "Samoa",
    region: "Pacific",
    offsetStr: "GMT+11:00",
  },
  {
    name: "HST",
    offset: -600,
    city: "",
    region: "HST",
    offsetStr: "GMT+10:00",
  },
  {
    name: "Pacific/Honolulu",
    offset: -600,
    city: "Honolulu",
    region: "Pacific",
    offsetStr: "GMT+10:00",
  },
  {
    name: "Pacific/Johnston",
    offset: -600,
    city: "Johnston",
    region: "Pacific",
    offsetStr: "GMT+10:00",
  },
  {
    name: "Pacific/Rarotonga",
    offset: -600,
    city: "Rarotonga",
    region: "Pacific",
    offsetStr: "GMT+10:00",
  },
  {
    name: "Pacific/Tahiti",
    offset: -600,
    city: "Tahiti",
    region: "Pacific",
    offsetStr: "GMT+10:00",
  },
  {
    name: "Pacific/Marquesas",
    offset: -570,
    city: "Marquesas",
    region: "Pacific",
    offsetStr: "GMT+09:30",
  },
  {
    name: "America/Adak",
    offset: -540,
    city: "Adak",
    region: "America",
    offsetStr: "GMT+09:00",
  },
  {
    name: "America/Atka",
    offset: -540,
    city: "Atka",
    region: "America",
    offsetStr: "GMT+09:00",
  },
  {
    name: "Pacific/Gambier",
    offset: -540,
    city: "Gambier",
    region: "Pacific",
    offsetStr: "GMT+09:00",
  },
  {
    name: "America/Anchorage",
    offset: -480,
    city: "Anchorage",
    region: "America",
    offsetStr: "GMT+08:00",
  },
  {
    name: "America/Juneau",
    offset: -480,
    city: "Juneau",
    region: "America",
    offsetStr: "GMT+08:00",
  },
  {
    name: "America/Metlakatla",
    offset: -480,
    city: "Metlakatla",
    region: "America",
    offsetStr: "GMT+08:00",
  },
  {
    name: "America/Nome",
    offset: -480,
    city: "Nome",
    region: "America",
    offsetStr: "GMT+08:00",
  },
  {
    name: "America/Sitka",
    offset: -480,
    city: "Sitka",
    region: "America",
    offsetStr: "GMT+08:00",
  },
  {
    name: "America/Yakutat",
    offset: -480,
    city: "Yakutat",
    region: "America",
    offsetStr: "GMT+08:00",
  },
  {
    name: "Pacific/Pitcairn",
    offset: -480,
    city: "Pitcairn",
    region: "Pacific",
    offsetStr: "GMT+08:00",
  },
  {
    name: "America/Creston",
    offset: -420,
    city: "Creston",
    region: "America",
    offsetStr: "GMT+07:00",
  },
  {
    name: "America/Dawson",
    offset: -420,
    city: "Dawson",
    region: "America",
    offsetStr: "GMT+07:00",
  },
  {
    name: "America/Dawson_Creek",
    offset: -420,
    city: "Dawson Creek",
    region: "America",
    offsetStr: "GMT+07:00",
  },
  {
    name: "America/Ensenada",
    offset: -420,
    city: "Ensenada",
    region: "America",
    offsetStr: "GMT+07:00",
  },
  {
    name: "America/Fort_Nelson",
    offset: -420,
    city: "Fort Nelson",
    region: "America",
    offsetStr: "GMT+07:00",
  },
  {
    name: "America/Hermosillo",
    offset: -420,
    city: "Hermosillo",
    region: "America",
    offsetStr: "GMT+07:00",
  },
  {
    name: "America/Los_Angeles",
    offset: -420,
    city: "Los Angeles",
    region: "America",
    offsetStr: "GMT+07:00",
  },
  {
    name: "America/Mazatlan",
    offset: -420,
    city: "Mazatlan",
    region: "America",
    offsetStr: "GMT+07:00",
  },
  {
    name: "America/Phoenix",
    offset: -420,
    city: "Phoenix",
    region: "America",
    offsetStr: "GMT+07:00",
  },
  {
    name: "America/Santa_Isabel",
    offset: -420,
    city: "Santa Isabel",
    region: "America",
    offsetStr: "GMT+07:00",
  },
  {
    name: "America/Tijuana",
    offset: -420,
    city: "Tijuana",
    region: "America",
    offsetStr: "GMT+07:00",
  },
  {
    name: "America/Vancouver",
    offset: -420,
    city: "Vancouver",
    region: "America",
    offsetStr: "GMT+07:00",
  },
  {
    name: "America/Whitehorse",
    offset: -420,
    city: "Whitehorse",
    region: "America",
    offsetStr: "GMT+07:00",
  },
  {
    name: "MST",
    offset: -420,
    city: "",
    region: "MST",
    offsetStr: "GMT+07:00",
  },
  {
    name: "PST8PDT",
    offset: -420,
    city: "",
    region: "PST8PDT",
    offsetStr: "GMT+07:00",
  },
  {
    name: "America/Bahia_Banderas",
    offset: -360,
    city: "Bahia Banderas",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Belize",
    offset: -360,
    city: "Belize",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Boise",
    offset: -360,
    city: "Boise",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Cambridge_Bay",
    offset: -360,
    city: "Cambridge Bay",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Chihuahua",
    offset: -360,
    city: "Chihuahua",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Ciudad_Juarez",
    offset: -360,
    city: "Ciudad Juarez",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Costa_Rica",
    offset: -360,
    city: "Costa Rica",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Denver",
    offset: -360,
    city: "Denver",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Edmonton",
    offset: -360,
    city: "Edmonton",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/El_Salvador",
    offset: -360,
    city: "El Salvador",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Guatemala",
    offset: -360,
    city: "Guatemala",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Inuvik",
    offset: -360,
    city: "Inuvik",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Managua",
    offset: -360,
    city: "Managua",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Merida",
    offset: -360,
    city: "Merida",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Mexico_City",
    offset: -360,
    city: "Mexico City",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Monterrey",
    offset: -360,
    city: "Monterrey",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Regina",
    offset: -360,
    city: "Regina",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Shiprock",
    offset: -360,
    city: "Shiprock",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Swift_Current",
    offset: -360,
    city: "Swift Current",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Tegucigalpa",
    offset: -360,
    city: "Tegucigalpa",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Yellowknife",
    offset: -360,
    city: "Yellowknife",
    region: "America",
    offsetStr: "GMT+06:00",
  },
  {
    name: "MST7MDT",
    offset: -360,
    city: "",
    region: "MST7MDT",
    offsetStr: "GMT+06:00",
  },
  {
    name: "Pacific/Galapagos",
    offset: -360,
    city: "Galapagos",
    region: "Pacific",
    offsetStr: "GMT+06:00",
  },
  {
    name: "America/Atikokan",
    offset: -300,
    city: "Atikokan",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Bogota",
    offset: -300,
    city: "Bogota",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Cancun",
    offset: -300,
    city: "Cancun",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Cayman",
    offset: -300,
    city: "Cayman",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Chicago",
    offset: -300,
    city: "Chicago",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Coral_Harbour",
    offset: -300,
    city: "Coral Harbour",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Eirunepe",
    offset: -300,
    city: "Eirunepe",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Guayaquil",
    offset: -300,
    city: "Guayaquil",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Indiana/Knox",
    offset: -300,
    city: "Indiana/Knox",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Indiana/Tell_City",
    offset: -300,
    city: "Indiana/Tell City",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Jamaica",
    offset: -300,
    city: "Jamaica",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Knox_IN",
    offset: -300,
    city: "Knox IN",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Lima",
    offset: -300,
    city: "Lima",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Matamoros",
    offset: -300,
    city: "Matamoros",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Menominee",
    offset: -300,
    city: "Menominee",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/North_Dakota/Beulah",
    offset: -300,
    city: "North Dakota/Beulah",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/North_Dakota/Center",
    offset: -300,
    city: "North Dakota/Center",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/North_Dakota/New_Salem",
    offset: -300,
    city: "North Dakota/New Salem",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Ojinaga",
    offset: -300,
    city: "Ojinaga",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Panama",
    offset: -300,
    city: "Panama",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Porto_Acre",
    offset: -300,
    city: "Porto Acre",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Rainy_River",
    offset: -300,
    city: "Rainy River",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Rankin_Inlet",
    offset: -300,
    city: "Rankin Inlet",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Resolute",
    offset: -300,
    city: "Resolute",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Rio_Branco",
    offset: -300,
    city: "Rio Branco",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Winnipeg",
    offset: -300,
    city: "Winnipeg",
    region: "America",
    offsetStr: "GMT+05:00",
  },
  {
    name: "CST6CDT",
    offset: -300,
    city: "",
    region: "CST6CDT",
    offsetStr: "GMT+05:00",
  },
  {
    name: "EST",
    offset: -300,
    city: "",
    region: "EST",
    offsetStr: "GMT+05:00",
  },
  {
    name: "Pacific/Easter",
    offset: -300,
    city: "Easter",
    region: "Pacific",
    offsetStr: "GMT+05:00",
  },
  {
    name: "America/Anguilla",
    offset: -240,
    city: "Anguilla",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Antigua",
    offset: -240,
    city: "Antigua",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Aruba",
    offset: -240,
    city: "Aruba",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Barbados",
    offset: -240,
    city: "Barbados",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Blanc-Sablon",
    offset: -240,
    city: "Blanc-Sablon",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Boa_Vista",
    offset: -240,
    city: "Boa Vista",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Campo_Grande",
    offset: -240,
    city: "Campo Grande",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Caracas",
    offset: -240,
    city: "Caracas",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Cuiaba",
    offset: -240,
    city: "Cuiaba",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Curacao",
    offset: -240,
    city: "Curacao",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Detroit",
    offset: -240,
    city: "Detroit",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Dominica",
    offset: -240,
    city: "Dominica",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Fort_Wayne",
    offset: -240,
    city: "Fort Wayne",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Grand_Turk",
    offset: -240,
    city: "Grand Turk",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Grenada",
    offset: -240,
    city: "Grenada",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Guadeloupe",
    offset: -240,
    city: "Guadeloupe",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Guyana",
    offset: -240,
    city: "Guyana",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Havana",
    offset: -240,
    city: "Havana",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Indiana/Indianapolis",
    offset: -240,
    city: "Indiana/Indianapolis",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Indiana/Marengo",
    offset: -240,
    city: "Indiana/Marengo",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Indiana/Petersburg",
    offset: -240,
    city: "Indiana/Petersburg",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Indiana/Vevay",
    offset: -240,
    city: "Indiana/Vevay",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Indiana/Vincennes",
    offset: -240,
    city: "Indiana/Vincennes",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Indiana/Winamac",
    offset: -240,
    city: "Indiana/Winamac",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Indianapolis",
    offset: -240,
    city: "Indianapolis",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Iqaluit",
    offset: -240,
    city: "Iqaluit",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Kentucky/Louisville",
    offset: -240,
    city: "Kentucky/Louisville",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Kentucky/Monticello",
    offset: -240,
    city: "Kentucky/Monticello",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Kralendijk",
    offset: -240,
    city: "Kralendijk",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/La_Paz",
    offset: -240,
    city: "La Paz",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Louisville",
    offset: -240,
    city: "Louisville",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Lower_Princes",
    offset: -240,
    city: "Lower Princes",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Manaus",
    offset: -240,
    city: "Manaus",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Marigot",
    offset: -240,
    city: "Marigot",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Martinique",
    offset: -240,
    city: "Martinique",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Montreal",
    offset: -240,
    city: "Montreal",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Montserrat",
    offset: -240,
    city: "Montserrat",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Nassau",
    offset: -240,
    city: "Nassau",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/New_York",
    offset: -240,
    city: "New York",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Nipigon",
    offset: -240,
    city: "Nipigon",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Pangnirtung",
    offset: -240,
    city: "Pangnirtung",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Port-au-Prince",
    offset: -240,
    city: "Port-au-Prince",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Port_of_Spain",
    offset: -240,
    city: "Port of Spain",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Porto_Velho",
    offset: -240,
    city: "Porto Velho",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Puerto_Rico",
    offset: -240,
    city: "Puerto Rico",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Santo_Domingo",
    offset: -240,
    city: "Santo Domingo",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/St_Barthelemy",
    offset: -240,
    city: "St Barthelemy",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/St_Kitts",
    offset: -240,
    city: "St Kitts",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/St_Lucia",
    offset: -240,
    city: "St Lucia",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/St_Thomas",
    offset: -240,
    city: "St Thomas",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/St_Vincent",
    offset: -240,
    city: "St Vincent",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Thunder_Bay",
    offset: -240,
    city: "Thunder Bay",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Toronto",
    offset: -240,
    city: "Toronto",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Tortola",
    offset: -240,
    city: "Tortola",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Virgin",
    offset: -240,
    city: "Virgin",
    region: "America",
    offsetStr: "GMT+04:00",
  },
  {
    name: "EST5EDT",
    offset: -240,
    city: "",
    region: "EST5EDT",
    offsetStr: "GMT+04:00",
  },
  {
    name: "America/Araguaina",
    offset: -180,
    city: "Araguaina",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Argentina/Buenos_Aires",
    offset: -180,
    city: "Argentina/Buenos Aires",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Argentina/Catamarca",
    offset: -180,
    city: "Argentina/Catamarca",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Argentina/ComodRivadavia",
    offset: -180,
    city: "Argentina/ComodRivadavia",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Argentina/Cordoba",
    offset: -180,
    city: "Argentina/Cordoba",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Argentina/Jujuy",
    offset: -180,
    city: "Argentina/Jujuy",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Argentina/La_Rioja",
    offset: -180,
    city: "Argentina/La Rioja",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Argentina/Mendoza",
    offset: -180,
    city: "Argentina/Mendoza",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Argentina/Rio_Gallegos",
    offset: -180,
    city: "Argentina/Rio Gallegos",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Argentina/Salta",
    offset: -180,
    city: "Argentina/Salta",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Argentina/San_Juan",
    offset: -180,
    city: "Argentina/San Juan",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Argentina/San_Luis",
    offset: -180,
    city: "Argentina/San Luis",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Argentina/Tucuman",
    offset: -180,
    city: "Argentina/Tucuman",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Argentina/Ushuaia",
    offset: -180,
    city: "Argentina/Ushuaia",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Asuncion",
    offset: -180,
    city: "Asuncion",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Bahia",
    offset: -180,
    city: "Bahia",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Belem",
    offset: -180,
    city: "Belem",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Buenos_Aires",
    offset: -180,
    city: "Buenos Aires",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Catamarca",
    offset: -180,
    city: "Catamarca",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Cayenne",
    offset: -180,
    city: "Cayenne",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Cordoba",
    offset: -180,
    city: "Cordoba",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Fortaleza",
    offset: -180,
    city: "Fortaleza",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Glace_Bay",
    offset: -180,
    city: "Glace Bay",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Goose_Bay",
    offset: -180,
    city: "Goose Bay",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Halifax",
    offset: -180,
    city: "Halifax",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Jujuy",
    offset: -180,
    city: "Jujuy",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Maceio",
    offset: -180,
    city: "Maceio",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Mendoza",
    offset: -180,
    city: "Mendoza",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Moncton",
    offset: -180,
    city: "Moncton",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Montevideo",
    offset: -180,
    city: "Montevideo",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Paramaribo",
    offset: -180,
    city: "Paramaribo",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Punta_Arenas",
    offset: -180,
    city: "Punta Arenas",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Recife",
    offset: -180,
    city: "Recife",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Rosario",
    offset: -180,
    city: "Rosario",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Santarem",
    offset: -180,
    city: "Santarem",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Santiago",
    offset: -180,
    city: "Santiago",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Sao_Paulo",
    offset: -180,
    city: "Sao Paulo",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/Thule",
    offset: -180,
    city: "Thule",
    region: "America",
    offsetStr: "GMT+03:00",
  },
  {
    name: "Antarctica/Palmer",
    offset: -180,
    city: "Palmer",
    region: "Antarctica",
    offsetStr: "GMT+03:00",
  },
  {
    name: "Antarctica/Rothera",
    offset: -180,
    city: "Rothera",
    region: "Antarctica",
    offsetStr: "GMT+03:00",
  },
  {
    name: "Atlantic/Bermuda",
    offset: -180,
    city: "Bermuda",
    region: "Atlantic",
    offsetStr: "GMT+03:00",
  },
  {
    name: "Atlantic/Stanley",
    offset: -180,
    city: "Stanley",
    region: "Atlantic",
    offsetStr: "GMT+03:00",
  },
  {
    name: "America/St_Johns",
    offset: -150,
    city: "St Johns",
    region: "America",
    offsetStr: "GMT+02:30",
  },
  {
    name: "America/Miquelon",
    offset: -120,
    city: "Miquelon",
    region: "America",
    offsetStr: "GMT+02:00",
  },
  {
    name: "America/Noronha",
    offset: -120,
    city: "Noronha",
    region: "America",
    offsetStr: "GMT+02:00",
  },
  {
    name: "Atlantic/South_Georgia",
    offset: -120,
    city: "South Georgia",
    region: "Atlantic",
    offsetStr: "GMT+02:00",
  },
  {
    name: "America/Godthab",
    offset: -60,
    city: "Godthab",
    region: "America",
    offsetStr: "GMT+01:00",
  },
  {
    name: "America/Nuuk",
    offset: -60,
    city: "Nuuk",
    region: "America",
    offsetStr: "GMT+01:00",
  },
  {
    name: "America/Scoresbysund",
    offset: -60,
    city: "Scoresbysund",
    region: "America",
    offsetStr: "GMT+01:00",
  },
  {
    name: "Atlantic/Cape_Verde",
    offset: -60,
    city: "Cape Verde",
    region: "Atlantic",
    offsetStr: "GMT+01:00",
  },
  {
    name: "Africa/Abidjan",
    offset: 0,
    city: "Abidjan",
    region: "Africa",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Africa/Accra",
    offset: 0,
    city: "Accra",
    region: "Africa",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Africa/Bamako",
    offset: 0,
    city: "Bamako",
    region: "Africa",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Africa/Banjul",
    offset: 0,
    city: "Banjul",
    region: "Africa",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Africa/Bissau",
    offset: 0,
    city: "Bissau",
    region: "Africa",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Africa/Conakry",
    offset: 0,
    city: "Conakry",
    region: "Africa",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Africa/Dakar",
    offset: 0,
    city: "Dakar",
    region: "Africa",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Africa/Freetown",
    offset: 0,
    city: "Freetown",
    region: "Africa",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Africa/Lome",
    offset: 0,
    city: "Lome",
    region: "Africa",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Africa/Monrovia",
    offset: 0,
    city: "Monrovia",
    region: "Africa",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Africa/Nouakchott",
    offset: 0,
    city: "Nouakchott",
    region: "Africa",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Africa/Ouagadougou",
    offset: 0,
    city: "Ouagadougou",
    region: "Africa",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Africa/Sao_Tome",
    offset: 0,
    city: "Sao Tome",
    region: "Africa",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Africa/Timbuktu",
    offset: 0,
    city: "Timbuktu",
    region: "Africa",
    offsetStr: "GMT+00:00",
  },
  {
    name: "America/Danmarkshavn",
    offset: 0,
    city: "Danmarkshavn",
    region: "America",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Atlantic/Azores",
    offset: 0,
    city: "Azores",
    region: "Atlantic",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Atlantic/Reykjavik",
    offset: 0,
    city: "Reykjavik",
    region: "Atlantic",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Atlantic/St_Helena",
    offset: 0,
    city: "St Helena",
    region: "Atlantic",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Etc/Greenwich",
    offset: 0,
    city: "Greenwich",
    region: "Etc",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Etc/UCT",
    offset: 0,
    city: "UCT",
    region: "Etc",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Etc/UTC",
    offset: 0,
    city: "UTC",
    region: "Etc",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Etc/Universal",
    offset: 0,
    city: "Universal",
    region: "Etc",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Etc/Zulu",
    offset: 0,
    city: "Zulu",
    region: "Etc",
    offsetStr: "GMT+00:00",
  },
  {
    name: "GMT+0",
    offset: 0,
    city: "",
    region: "GMT+0",
    offsetStr: "GMT+00:00",
  },
  {
    name: "GMT-0",
    offset: 0,
    city: "",
    region: "GMT-0",
    offsetStr: "GMT+00:00",
  },
  {
    name: "GMT0",
    offset: 0,
    city: "",
    region: "GMT0",
    offsetStr: "GMT+00:00",
  },
  {
    name: "UTC",
    offset: 0,
    city: "",
    region: "UTC",
    offsetStr: "GMT+00:00",
  },
  {
    name: "Africa/Algiers",
    offset: 60,
    city: "Algiers",
    region: "Africa",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Africa/Bangui",
    offset: 60,
    city: "Bangui",
    region: "Africa",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Africa/Brazzaville",
    offset: 60,
    city: "Brazzaville",
    region: "Africa",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Africa/Casablanca",
    offset: 60,
    city: "Casablanca",
    region: "Africa",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Africa/Douala",
    offset: 60,
    city: "Douala",
    region: "Africa",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Africa/El_Aaiun",
    offset: 60,
    city: "El Aaiun",
    region: "Africa",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Africa/Kinshasa",
    offset: 60,
    city: "Kinshasa",
    region: "Africa",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Africa/Lagos",
    offset: 60,
    city: "Lagos",
    region: "Africa",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Africa/Libreville",
    offset: 60,
    city: "Libreville",
    region: "Africa",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Africa/Luanda",
    offset: 60,
    city: "Luanda",
    region: "Africa",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Africa/Malabo",
    offset: 60,
    city: "Malabo",
    region: "Africa",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Africa/Ndjamena",
    offset: 60,
    city: "Ndjamena",
    region: "Africa",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Africa/Niamey",
    offset: 60,
    city: "Niamey",
    region: "Africa",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Africa/Porto-Novo",
    offset: 60,
    city: "Porto-Novo",
    region: "Africa",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Africa/Tunis",
    offset: 60,
    city: "Tunis",
    region: "Africa",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Atlantic/Canary",
    offset: 60,
    city: "Canary",
    region: "Atlantic",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Atlantic/Faeroe",
    offset: 60,
    city: "Faeroe",
    region: "Atlantic",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Atlantic/Faroe",
    offset: 60,
    city: "Faroe",
    region: "Atlantic",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Atlantic/Madeira",
    offset: 60,
    city: "Madeira",
    region: "Atlantic",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Europe/Belfast",
    offset: 60,
    city: "Belfast",
    region: "Europe",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Europe/Dublin",
    offset: 60,
    city: "Dublin",
    region: "Europe",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Europe/Guernsey",
    offset: 60,
    city: "Guernsey",
    region: "Europe",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Europe/Isle_of_Man",
    offset: 60,
    city: "Isle of Man",
    region: "Europe",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Europe/Jersey",
    offset: 60,
    city: "Jersey",
    region: "Europe",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Europe/Lisbon",
    offset: 60,
    city: "Lisbon",
    region: "Europe",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Europe/London",
    offset: 60,
    city: "London",
    region: "Europe",
    offsetStr: "GMT-01:00",
  },
  {
    name: "GB-Eire",
    offset: 60,
    city: "",
    region: "GB-Eire",
    offsetStr: "GMT-01:00",
  },
  {
    name: "WET",
    offset: 60,
    city: "",
    region: "WET",
    offsetStr: "GMT-01:00",
  },
  {
    name: "Africa/Blantyre",
    offset: 120,
    city: "Blantyre",
    region: "Africa",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Africa/Bujumbura",
    offset: 120,
    city: "Bujumbura",
    region: "Africa",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Africa/Ceuta",
    offset: 120,
    city: "Ceuta",
    region: "Africa",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Africa/Gaborone",
    offset: 120,
    city: "Gaborone",
    region: "Africa",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Africa/Harare",
    offset: 120,
    city: "Harare",
    region: "Africa",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Africa/Johannesburg",
    offset: 120,
    city: "Johannesburg",
    region: "Africa",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Africa/Juba",
    offset: 120,
    city: "Juba",
    region: "Africa",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Africa/Khartoum",
    offset: 120,
    city: "Khartoum",
    region: "Africa",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Africa/Kigali",
    offset: 120,
    city: "Kigali",
    region: "Africa",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Africa/Lubumbashi",
    offset: 120,
    city: "Lubumbashi",
    region: "Africa",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Africa/Lusaka",
    offset: 120,
    city: "Lusaka",
    region: "Africa",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Africa/Maputo",
    offset: 120,
    city: "Maputo",
    region: "Africa",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Africa/Maseru",
    offset: 120,
    city: "Maseru",
    region: "Africa",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Africa/Mbabane",
    offset: 120,
    city: "Mbabane",
    region: "Africa",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Africa/Tripoli",
    offset: 120,
    city: "Tripoli",
    region: "Africa",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Africa/Windhoek",
    offset: 120,
    city: "Windhoek",
    region: "Africa",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Antarctica/Troll",
    offset: 120,
    city: "Troll",
    region: "Antarctica",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Arctic/Longyearbyen",
    offset: 120,
    city: "Longyearbyen",
    region: "Arctic",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Atlantic/Jan_Mayen",
    offset: 120,
    city: "Jan Mayen",
    region: "Atlantic",
    offsetStr: "GMT-02:00",
  },
  {
    name: "CET",
    offset: 120,
    city: "",
    region: "CET",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Amsterdam",
    offset: 120,
    city: "Amsterdam",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Andorra",
    offset: 120,
    city: "Andorra",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Belgrade",
    offset: 120,
    city: "Belgrade",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Berlin",
    offset: 120,
    city: "Berlin",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Bratislava",
    offset: 120,
    city: "Bratislava",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Brussels",
    offset: 120,
    city: "Brussels",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Budapest",
    offset: 120,
    city: "Budapest",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Busingen",
    offset: 120,
    city: "Busingen",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Copenhagen",
    offset: 120,
    city: "Copenhagen",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Gibraltar",
    offset: 120,
    city: "Gibraltar",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Kaliningrad",
    offset: 120,
    city: "Kaliningrad",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Ljubljana",
    offset: 120,
    city: "Ljubljana",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Luxembourg",
    offset: 120,
    city: "Luxembourg",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Madrid",
    offset: 120,
    city: "Madrid",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Malta",
    offset: 120,
    city: "Malta",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Monaco",
    offset: 120,
    city: "Monaco",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Oslo",
    offset: 120,
    city: "Oslo",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Paris",
    offset: 120,
    city: "Paris",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Podgorica",
    offset: 120,
    city: "Podgorica",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Prague",
    offset: 120,
    city: "Prague",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Rome",
    offset: 120,
    city: "Rome",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/San_Marino",
    offset: 120,
    city: "San Marino",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Sarajevo",
    offset: 120,
    city: "Sarajevo",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Skopje",
    offset: 120,
    city: "Skopje",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Stockholm",
    offset: 120,
    city: "Stockholm",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Tirane",
    offset: 120,
    city: "Tirane",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Vaduz",
    offset: 120,
    city: "Vaduz",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Vatican",
    offset: 120,
    city: "Vatican",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Vienna",
    offset: 120,
    city: "Vienna",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Warsaw",
    offset: 120,
    city: "Warsaw",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Zagreb",
    offset: 120,
    city: "Zagreb",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Europe/Zurich",
    offset: 120,
    city: "Zurich",
    region: "Europe",
    offsetStr: "GMT-02:00",
  },
  {
    name: "MET",
    offset: 120,
    city: "",
    region: "MET",
    offsetStr: "GMT-02:00",
  },
  {
    name: "Africa/Addis_Ababa",
    offset: 180,
    city: "Addis Ababa",
    region: "Africa",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Africa/Asmara",
    offset: 180,
    city: "Asmara",
    region: "Africa",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Africa/Asmera",
    offset: 180,
    city: "Asmera",
    region: "Africa",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Africa/Cairo",
    offset: 180,
    city: "Cairo",
    region: "Africa",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Africa/Dar_es_Salaam",
    offset: 180,
    city: "Dar es Salaam",
    region: "Africa",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Africa/Djibouti",
    offset: 180,
    city: "Djibouti",
    region: "Africa",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Africa/Kampala",
    offset: 180,
    city: "Kampala",
    region: "Africa",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Africa/Mogadishu",
    offset: 180,
    city: "Mogadishu",
    region: "Africa",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Africa/Nairobi",
    offset: 180,
    city: "Nairobi",
    region: "Africa",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Antarctica/Syowa",
    offset: 180,
    city: "Syowa",
    region: "Antarctica",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Asia/Aden",
    offset: 180,
    city: "Aden",
    region: "Asia",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Asia/Amman",
    offset: 180,
    city: "Amman",
    region: "Asia",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Asia/Baghdad",
    offset: 180,
    city: "Baghdad",
    region: "Asia",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Asia/Bahrain",
    offset: 180,
    city: "Bahrain",
    region: "Asia",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Asia/Beirut",
    offset: 180,
    city: "Beirut",
    region: "Asia",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Asia/Damascus",
    offset: 180,
    city: "Damascus",
    region: "Asia",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Asia/Famagusta",
    offset: 180,
    city: "Famagusta",
    region: "Asia",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Asia/Gaza",
    offset: 180,
    city: "Gaza",
    region: "Asia",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Asia/Hebron",
    offset: 180,
    city: "Hebron",
    region: "Asia",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Asia/Istanbul",
    offset: 180,
    city: "Istanbul",
    region: "Asia",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Asia/Jerusalem",
    offset: 180,
    city: "Jerusalem",
    region: "Asia",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Asia/Kuwait",
    offset: 180,
    city: "Kuwait",
    region: "Asia",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Asia/Nicosia",
    offset: 180,
    city: "Nicosia",
    region: "Asia",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Asia/Qatar",
    offset: 180,
    city: "Qatar",
    region: "Asia",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Asia/Riyadh",
    offset: 180,
    city: "Riyadh",
    region: "Asia",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Asia/Tel_Aviv",
    offset: 180,
    city: "Tel Aviv",
    region: "Asia",
    offsetStr: "GMT-03:00",
  },
  {
    name: "EET",
    offset: 180,
    city: "",
    region: "EET",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Athens",
    offset: 180,
    city: "Athens",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Bucharest",
    offset: 180,
    city: "Bucharest",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Chisinau",
    offset: 180,
    city: "Chisinau",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Helsinki",
    offset: 180,
    city: "Helsinki",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Istanbul",
    offset: 180,
    city: "Istanbul",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Kiev",
    offset: 180,
    city: "Kiev",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Kirov",
    offset: 180,
    city: "Kirov",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Kyiv",
    offset: 180,
    city: "Kyiv",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Mariehamn",
    offset: 180,
    city: "Mariehamn",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Minsk",
    offset: 180,
    city: "Minsk",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Moscow",
    offset: 180,
    city: "Moscow",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Nicosia",
    offset: 180,
    city: "Nicosia",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Riga",
    offset: 180,
    city: "Riga",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Simferopol",
    offset: 180,
    city: "Simferopol",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Sofia",
    offset: 180,
    city: "Sofia",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Tallinn",
    offset: 180,
    city: "Tallinn",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Tiraspol",
    offset: 180,
    city: "Tiraspol",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Uzhgorod",
    offset: 180,
    city: "Uzhgorod",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Vilnius",
    offset: 180,
    city: "Vilnius",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Volgograd",
    offset: 180,
    city: "Volgograd",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Europe/Zaporozhye",
    offset: 180,
    city: "Zaporozhye",
    region: "Europe",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Indian/Antananarivo",
    offset: 180,
    city: "Antananarivo",
    region: "Indian",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Indian/Comoro",
    offset: 180,
    city: "Comoro",
    region: "Indian",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Indian/Mayotte",
    offset: 180,
    city: "Mayotte",
    region: "Indian",
    offsetStr: "GMT-03:00",
  },
  {
    name: "Asia/Tehran",
    offset: 210,
    city: "Tehran",
    region: "Asia",
    offsetStr: "GMT-03:30",
  },
  {
    name: "Asia/Baku",
    offset: 240,
    city: "Baku",
    region: "Asia",
    offsetStr: "GMT-04:00",
  },
  {
    name: "Asia/Dubai",
    offset: 240,
    city: "Dubai",
    region: "Asia",
    offsetStr: "GMT-04:00",
  },
  {
    name: "Asia/Muscat",
    offset: 240,
    city: "Muscat",
    region: "Asia",
    offsetStr: "GMT-04:00",
  },
  {
    name: "Asia/Tbilisi",
    offset: 240,
    city: "Tbilisi",
    region: "Asia",
    offsetStr: "GMT-04:00",
  },
  {
    name: "Asia/Yerevan",
    offset: 240,
    city: "Yerevan",
    region: "Asia",
    offsetStr: "GMT-04:00",
  },
  {
    name: "Europe/Astrakhan",
    offset: 240,
    city: "Astrakhan",
    region: "Europe",
    offsetStr: "GMT-04:00",
  },
  {
    name: "Europe/Samara",
    offset: 240,
    city: "Samara",
    region: "Europe",
    offsetStr: "GMT-04:00",
  },
  {
    name: "Europe/Saratov",
    offset: 240,
    city: "Saratov",
    region: "Europe",
    offsetStr: "GMT-04:00",
  },
  {
    name: "Europe/Ulyanovsk",
    offset: 240,
    city: "Ulyanovsk",
    region: "Europe",
    offsetStr: "GMT-04:00",
  },
  {
    name: "Indian/Mahe",
    offset: 240,
    city: "Mahe",
    region: "Indian",
    offsetStr: "GMT-04:00",
  },
  {
    name: "Indian/Mauritius",
    offset: 240,
    city: "Mauritius",
    region: "Indian",
    offsetStr: "GMT-04:00",
  },
  {
    name: "Indian/Reunion",
    offset: 240,
    city: "Reunion",
    region: "Indian",
    offsetStr: "GMT-04:00",
  },
  {
    name: "Asia/Kabul",
    offset: 270,
    city: "Kabul",
    region: "Asia",
    offsetStr: "GMT-04:30",
  },
  {
    name: "Antarctica/Mawson",
    offset: 300,
    city: "Mawson",
    region: "Antarctica",
    offsetStr: "GMT-05:00",
  },
  {
    name: "Antarctica/Vostok",
    offset: 300,
    city: "Vostok",
    region: "Antarctica",
    offsetStr: "GMT-05:00",
  },
  {
    name: "Asia/Almaty",
    offset: 300,
    city: "Almaty",
    region: "Asia",
    offsetStr: "GMT-05:00",
  },
  {
    name: "Asia/Aqtau",
    offset: 300,
    city: "Aqtau",
    region: "Asia",
    offsetStr: "GMT-05:00",
  },
  {
    name: "Asia/Aqtobe",
    offset: 300,
    city: "Aqtobe",
    region: "Asia",
    offsetStr: "GMT-05:00",
  },
  {
    name: "Asia/Ashgabat",
    offset: 300,
    city: "Ashgabat",
    region: "Asia",
    offsetStr: "GMT-05:00",
  },
  {
    name: "Asia/Ashkhabad",
    offset: 300,
    city: "Ashkhabad",
    region: "Asia",
    offsetStr: "GMT-05:00",
  },
  {
    name: "Asia/Atyrau",
    offset: 300,
    city: "Atyrau",
    region: "Asia",
    offsetStr: "GMT-05:00",
  },
  {
    name: "Asia/Dushanbe",
    offset: 300,
    city: "Dushanbe",
    region: "Asia",
    offsetStr: "GMT-05:00",
  },
  {
    name: "Asia/Karachi",
    offset: 300,
    city: "Karachi",
    region: "Asia",
    offsetStr: "GMT-05:00",
  },
  {
    name: "Asia/Oral",
    offset: 300,
    city: "Oral",
    region: "Asia",
    offsetStr: "GMT-05:00",
  },
  {
    name: "Asia/Qostanay",
    offset: 300,
    city: "Qostanay",
    region: "Asia",
    offsetStr: "GMT-05:00",
  },
  {
    name: "Asia/Qyzylorda",
    offset: 300,
    city: "Qyzylorda",
    region: "Asia",
    offsetStr: "GMT-05:00",
  },
  {
    name: "Asia/Samarkand",
    offset: 300,
    city: "Samarkand",
    region: "Asia",
    offsetStr: "GMT-05:00",
  },
  {
    name: "Asia/Tashkent",
    offset: 300,
    city: "Tashkent",
    region: "Asia",
    offsetStr: "GMT-05:00",
  },
  {
    name: "Asia/Yekaterinburg",
    offset: 300,
    city: "Yekaterinburg",
    region: "Asia",
    offsetStr: "GMT-05:00",
  },
  {
    name: "Indian/Kerguelen",
    offset: 300,
    city: "Kerguelen",
    region: "Indian",
    offsetStr: "GMT-05:00",
  },
  {
    name: "Indian/Maldives",
    offset: 300,
    city: "Maldives",
    region: "Indian",
    offsetStr: "GMT-05:00",
  },
  {
    name: "Asia/Calcutta",
    offset: 330,
    city: "Calcutta",
    region: "Asia",
    offsetStr: "GMT-05:30",
  },
  {
    name: "Asia/Colombo",
    offset: 330,
    city: "Colombo",
    region: "Asia",
    offsetStr: "GMT-05:30",
  },
  {
    name: "Asia/Kolkata",
    offset: 330,
    city: "Kolkata",
    region: "Asia",
    offsetStr: "GMT-05:30",
  },
  {
    name: "Asia/Kathmandu",
    offset: 345,
    city: "Kathmandu",
    region: "Asia",
    offsetStr: "GMT-05:45",
  },
  {
    name: "Asia/Katmandu",
    offset: 345,
    city: "Katmandu",
    region: "Asia",
    offsetStr: "GMT-05:45",
  },
  {
    name: "Asia/Bishkek",
    offset: 360,
    city: "Bishkek",
    region: "Asia",
    offsetStr: "GMT-06:00",
  },
  {
    name: "Asia/Dacca",
    offset: 360,
    city: "Dacca",
    region: "Asia",
    offsetStr: "GMT-06:00",
  },
  {
    name: "Asia/Dhaka",
    offset: 360,
    city: "Dhaka",
    region: "Asia",
    offsetStr: "GMT-06:00",
  },
  {
    name: "Asia/Kashgar",
    offset: 360,
    city: "Kashgar",
    region: "Asia",
    offsetStr: "GMT-06:00",
  },
  {
    name: "Asia/Omsk",
    offset: 360,
    city: "Omsk",
    region: "Asia",
    offsetStr: "GMT-06:00",
  },
  {
    name: "Asia/Thimbu",
    offset: 360,
    city: "Thimbu",
    region: "Asia",
    offsetStr: "GMT-06:00",
  },
  {
    name: "Asia/Thimphu",
    offset: 360,
    city: "Thimphu",
    region: "Asia",
    offsetStr: "GMT-06:00",
  },
  {
    name: "Asia/Urumqi",
    offset: 360,
    city: "Urumqi",
    region: "Asia",
    offsetStr: "GMT-06:00",
  },
  {
    name: "Indian/Chagos",
    offset: 360,
    city: "Chagos",
    region: "Indian",
    offsetStr: "GMT-06:00",
  },
  {
    name: "Asia/Rangoon",
    offset: 390,
    city: "Rangoon",
    region: "Asia",
    offsetStr: "GMT-06:30",
  },
  {
    name: "Asia/Yangon",
    offset: 390,
    city: "Yangon",
    region: "Asia",
    offsetStr: "GMT-06:30",
  },
  {
    name: "Indian/Cocos",
    offset: 390,
    city: "Cocos",
    region: "Indian",
    offsetStr: "GMT-06:30",
  },
  {
    name: "Antarctica/Davis",
    offset: 420,
    city: "Davis",
    region: "Antarctica",
    offsetStr: "GMT-07:00",
  },
  {
    name: "Asia/Bangkok",
    offset: 420,
    city: "Bangkok",
    region: "Asia",
    offsetStr: "GMT-07:00",
  },
  {
    name: "Asia/Barnaul",
    offset: 420,
    city: "Barnaul",
    region: "Asia",
    offsetStr: "GMT-07:00",
  },
  {
    name: "Asia/Ho_Chi_Minh",
    offset: 420,
    city: "Ho Chi Minh",
    region: "Asia",
    offsetStr: "GMT-07:00",
  },
  {
    name: "Asia/Hovd",
    offset: 420,
    city: "Hovd",
    region: "Asia",
    offsetStr: "GMT-07:00",
  },
  {
    name: "Asia/Jakarta",
    offset: 420,
    city: "Jakarta",
    region: "Asia",
    offsetStr: "GMT-07:00",
  },
  {
    name: "Asia/Krasnoyarsk",
    offset: 420,
    city: "Krasnoyarsk",
    region: "Asia",
    offsetStr: "GMT-07:00",
  },
  {
    name: "Asia/Novokuznetsk",
    offset: 420,
    city: "Novokuznetsk",
    region: "Asia",
    offsetStr: "GMT-07:00",
  },
  {
    name: "Asia/Novosibirsk",
    offset: 420,
    city: "Novosibirsk",
    region: "Asia",
    offsetStr: "GMT-07:00",
  },
  {
    name: "Asia/Phnom_Penh",
    offset: 420,
    city: "Phnom Penh",
    region: "Asia",
    offsetStr: "GMT-07:00",
  },
  {
    name: "Asia/Pontianak",
    offset: 420,
    city: "Pontianak",
    region: "Asia",
    offsetStr: "GMT-07:00",
  },
  {
    name: "Asia/Saigon",
    offset: 420,
    city: "Saigon",
    region: "Asia",
    offsetStr: "GMT-07:00",
  },
  {
    name: "Asia/Tomsk",
    offset: 420,
    city: "Tomsk",
    region: "Asia",
    offsetStr: "GMT-07:00",
  },
  {
    name: "Asia/Vientiane",
    offset: 420,
    city: "Vientiane",
    region: "Asia",
    offsetStr: "GMT-07:00",
  },
  {
    name: "Indian/Christmas",
    offset: 420,
    city: "Christmas",
    region: "Indian",
    offsetStr: "GMT-07:00",
  },
  {
    name: "Antarctica/Casey",
    offset: 480,
    city: "Casey",
    region: "Antarctica",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Brunei",
    offset: 480,
    city: "Brunei",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Choibalsan",
    offset: 480,
    city: "Choibalsan",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Chongqing",
    offset: 480,
    city: "Chongqing",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Chungking",
    offset: 480,
    city: "Chungking",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Harbin",
    offset: 480,
    city: "Harbin",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Hong_Kong",
    offset: 480,
    city: "Hong Kong",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Irkutsk",
    offset: 480,
    city: "Irkutsk",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Kuala_Lumpur",
    offset: 480,
    city: "Kuala Lumpur",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Kuching",
    offset: 480,
    city: "Kuching",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Macao",
    offset: 480,
    city: "Macao",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Macau",
    offset: 480,
    city: "Macau",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Makassar",
    offset: 480,
    city: "Makassar",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Manila",
    offset: 480,
    city: "Manila",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Shanghai",
    offset: 480,
    city: "Shanghai",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Singapore",
    offset: 480,
    city: "Singapore",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Taipei",
    offset: 480,
    city: "Taipei",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Ujung_Pandang",
    offset: 480,
    city: "Ujung Pandang",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Ulaanbaatar",
    offset: 480,
    city: "Ulaanbaatar",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Asia/Ulan_Bator",
    offset: 480,
    city: "Ulan Bator",
    region: "Asia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Australia/Perth",
    offset: 480,
    city: "Perth",
    region: "Australia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Australia/West",
    offset: 480,
    city: "West",
    region: "Australia",
    offsetStr: "GMT-08:00",
  },
  {
    name: "Australia/Eucla",
    offset: 525,
    city: "Eucla",
    region: "Australia",
    offsetStr: "GMT-08:45",
  },
  {
    name: "Asia/Chita",
    offset: 540,
    city: "Chita",
    region: "Asia",
    offsetStr: "GMT-09:00",
  },
  {
    name: "Asia/Dili",
    offset: 540,
    city: "Dili",
    region: "Asia",
    offsetStr: "GMT-09:00",
  },
  {
    name: "Asia/Jayapura",
    offset: 540,
    city: "Jayapura",
    region: "Asia",
    offsetStr: "GMT-09:00",
  },
  {
    name: "Asia/Khandyga",
    offset: 540,
    city: "Khandyga",
    region: "Asia",
    offsetStr: "GMT-09:00",
  },
  {
    name: "Asia/Pyongyang",
    offset: 540,
    city: "Pyongyang",
    region: "Asia",
    offsetStr: "GMT-09:00",
  },
  {
    name: "Asia/Seoul",
    offset: 540,
    city: "Seoul",
    region: "Asia",
    offsetStr: "GMT-09:00",
  },
  {
    name: "Asia/Tokyo",
    offset: 540,
    city: "Tokyo",
    region: "Asia",
    offsetStr: "GMT-09:00",
  },
  {
    name: "Asia/Yakutsk",
    offset: 540,
    city: "Yakutsk",
    region: "Asia",
    offsetStr: "GMT-09:00",
  },
  {
    name: "Pacific/Palau",
    offset: 540,
    city: "Palau",
    region: "Pacific",
    offsetStr: "GMT-09:00",
  },
  {
    name: "Australia/Adelaide",
    offset: 570,
    city: "Adelaide",
    region: "Australia",
    offsetStr: "GMT-09:30",
  },
  {
    name: "Australia/Broken_Hill",
    offset: 570,
    city: "Broken Hill",
    region: "Australia",
    offsetStr: "GMT-09:30",
  },
  {
    name: "Australia/Darwin",
    offset: 570,
    city: "Darwin",
    region: "Australia",
    offsetStr: "GMT-09:30",
  },
  {
    name: "Australia/North",
    offset: 570,
    city: "North",
    region: "Australia",
    offsetStr: "GMT-09:30",
  },
  {
    name: "Australia/South",
    offset: 570,
    city: "South",
    region: "Australia",
    offsetStr: "GMT-09:30",
  },
  {
    name: "Australia/Yancowinna",
    offset: 570,
    city: "Yancowinna",
    region: "Australia",
    offsetStr: "GMT-09:30",
  },
  {
    name: "Antarctica/DumontDUrville",
    offset: 600,
    city: "DumontDUrville",
    region: "Antarctica",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Antarctica/Macquarie",
    offset: 600,
    city: "Macquarie",
    region: "Antarctica",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Asia/Ust-Nera",
    offset: 600,
    city: "Ust-Nera",
    region: "Asia",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Asia/Vladivostok",
    offset: 600,
    city: "Vladivostok",
    region: "Asia",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Australia/ACT",
    offset: 600,
    city: "ACT",
    region: "Australia",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Australia/Brisbane",
    offset: 600,
    city: "Brisbane",
    region: "Australia",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Australia/Canberra",
    offset: 600,
    city: "Canberra",
    region: "Australia",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Australia/Currie",
    offset: 600,
    city: "Currie",
    region: "Australia",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Australia/Hobart",
    offset: 600,
    city: "Hobart",
    region: "Australia",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Australia/Lindeman",
    offset: 600,
    city: "Lindeman",
    region: "Australia",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Australia/Melbourne",
    offset: 600,
    city: "Melbourne",
    region: "Australia",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Australia/NSW",
    offset: 600,
    city: "NSW",
    region: "Australia",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Australia/Queensland",
    offset: 600,
    city: "Queensland",
    region: "Australia",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Australia/Sydney",
    offset: 600,
    city: "Sydney",
    region: "Australia",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Australia/Tasmania",
    offset: 600,
    city: "Tasmania",
    region: "Australia",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Australia/Victoria",
    offset: 600,
    city: "Victoria",
    region: "Australia",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Pacific/Chuuk",
    offset: 600,
    city: "Chuuk",
    region: "Pacific",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Pacific/Guam",
    offset: 600,
    city: "Guam",
    region: "Pacific",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Pacific/Port_Moresby",
    offset: 600,
    city: "Port Moresby",
    region: "Pacific",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Pacific/Saipan",
    offset: 600,
    city: "Saipan",
    region: "Pacific",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Pacific/Truk",
    offset: 600,
    city: "Truk",
    region: "Pacific",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Pacific/Yap",
    offset: 600,
    city: "Yap",
    region: "Pacific",
    offsetStr: "GMT-10:00",
  },
  {
    name: "Australia/LHI",
    offset: 630,
    city: "LHI",
    region: "Australia",
    offsetStr: "GMT-10:30",
  },
  {
    name: "Australia/Lord_Howe",
    offset: 630,
    city: "Lord Howe",
    region: "Australia",
    offsetStr: "GMT-10:30",
  },
  {
    name: "Asia/Magadan",
    offset: 660,
    city: "Magadan",
    region: "Asia",
    offsetStr: "GMT-11:00",
  },
  {
    name: "Asia/Sakhalin",
    offset: 660,
    city: "Sakhalin",
    region: "Asia",
    offsetStr: "GMT-11:00",
  },
  {
    name: "Asia/Srednekolymsk",
    offset: 660,
    city: "Srednekolymsk",
    region: "Asia",
    offsetStr: "GMT-11:00",
  },
  {
    name: "Pacific/Bougainville",
    offset: 660,
    city: "Bougainville",
    region: "Pacific",
    offsetStr: "GMT-11:00",
  },
  {
    name: "Pacific/Efate",
    offset: 660,
    city: "Efate",
    region: "Pacific",
    offsetStr: "GMT-11:00",
  },
  {
    name: "Pacific/Guadalcanal",
    offset: 660,
    city: "Guadalcanal",
    region: "Pacific",
    offsetStr: "GMT-11:00",
  },
  {
    name: "Pacific/Kosrae",
    offset: 660,
    city: "Kosrae",
    region: "Pacific",
    offsetStr: "GMT-11:00",
  },
  {
    name: "Pacific/Norfolk",
    offset: 660,
    city: "Norfolk",
    region: "Pacific",
    offsetStr: "GMT-11:00",
  },
  {
    name: "Pacific/Noumea",
    offset: 660,
    city: "Noumea",
    region: "Pacific",
    offsetStr: "GMT-11:00",
  },
  {
    name: "Pacific/Pohnpei",
    offset: 660,
    city: "Pohnpei",
    region: "Pacific",
    offsetStr: "GMT-11:00",
  },
  {
    name: "Pacific/Ponape",
    offset: 660,
    city: "Ponape",
    region: "Pacific",
    offsetStr: "GMT-11:00",
  },
  {
    name: "Asia/Anadyr",
    offset: 720,
    city: "Anadyr",
    region: "Asia",
    offsetStr: "GMT-12:00",
  },
  {
    name: "Asia/Kamchatka",
    offset: 720,
    city: "Kamchatka",
    region: "Asia",
    offsetStr: "GMT-12:00",
  },
  {
    name: "Pacific/Fiji",
    offset: 720,
    city: "Fiji",
    region: "Pacific",
    offsetStr: "GMT-12:00",
  },
  {
    name: "Pacific/Funafuti",
    offset: 720,
    city: "Funafuti",
    region: "Pacific",
    offsetStr: "GMT-12:00",
  },
  {
    name: "Pacific/Kwajalein",
    offset: 720,
    city: "Kwajalein",
    region: "Pacific",
    offsetStr: "GMT-12:00",
  },
  {
    name: "Pacific/Majuro",
    offset: 720,
    city: "Majuro",
    region: "Pacific",
    offsetStr: "GMT-12:00",
  },
  {
    name: "Pacific/Nauru",
    offset: 720,
    city: "Nauru",
    region: "Pacific",
    offsetStr: "GMT-12:00",
  },
  {
    name: "Pacific/Tarawa",
    offset: 720,
    city: "Tarawa",
    region: "Pacific",
    offsetStr: "GMT-12:00",
  },
  {
    name: "Pacific/Wake",
    offset: 720,
    city: "Wake",
    region: "Pacific",
    offsetStr: "GMT-12:00",
  },
  {
    name: "Pacific/Wallis",
    offset: 720,
    city: "Wallis",
    region: "Pacific",
    offsetStr: "GMT-12:00",
  },
  {
    name: "Antarctica/McMurdo",
    offset: 780,
    city: "McMurdo",
    region: "Antarctica",
    offsetStr: "GMT-13:00",
  },
  {
    name: "Antarctica/South_Pole",
    offset: 780,
    city: "South Pole",
    region: "Antarctica",
    offsetStr: "GMT-13:00",
  },
  {
    name: "Pacific/Apia",
    offset: 780,
    city: "Apia",
    region: "Pacific",
    offsetStr: "GMT-13:00",
  },
  {
    name: "Pacific/Auckland",
    offset: 780,
    city: "Auckland",
    region: "Pacific",
    offsetStr: "GMT-13:00",
  },
  {
    name: "Pacific/Enderbury",
    offset: 780,
    city: "Enderbury",
    region: "Pacific",
    offsetStr: "GMT-13:00",
  },
  {
    name: "Pacific/Fakaofo",
    offset: 780,
    city: "Fakaofo",
    region: "Pacific",
    offsetStr: "GMT-13:00",
  },
  {
    name: "Pacific/Kanton",
    offset: 780,
    city: "Kanton",
    region: "Pacific",
    offsetStr: "GMT-13:00",
  },
  {
    name: "Pacific/Tongatapu",
    offset: 780,
    city: "Tongatapu",
    region: "Pacific",
    offsetStr: "GMT-13:00",
  },
  {
    name: "NZ-CHAT",
    offset: 825,
    city: "",
    region: "NZ-CHAT",
    offsetStr: "GMT-13:45",
  },
  {
    name: "Pacific/Chatham",
    offset: 825,
    city: "Chatham",
    region: "Pacific",
    offsetStr: "GMT-13:45",
  },
  {
    name: "Pacific/Kiritimati",
    offset: 840,
    city: "Kiritimati",
    region: "Pacific",
    offsetStr: "GMT-14:00",
  },
];
