export const formatDateForClickHouse = (date) => {
  return date.toISOString().replace("T", " ").replace("Z", "").slice(0, 23);
};

const timezones = [
  {
    name: "Pacific/Midway",
    offset: -660,
    utcOffsetStr: "GMT+11:00",
    region: "Pacific",
    city: "Midway",
    currentTime: "10:06 AM",
  },
  {
    name: "Pacific/Niue",
    offset: -660,
    utcOffsetStr: "GMT+11:00",
    region: "Pacific",
    city: "Niue",
    currentTime: "10:06 AM",
  },
  {
    name: "Pacific/Pago_Pago",
    offset: -660,
    utcOffsetStr: "GMT+11:00",
    region: "Pacific",
    city: "Pago Pago",
    currentTime: "10:06 AM",
  },
  {
    name: "Pacific/Samoa",
    offset: -660,
    utcOffsetStr: "GMT+11:00",
    region: "Pacific",
    city: "Samoa",
    currentTime: "10:06 AM",
  },
  {
    name: "HST",
    offset: -600,
    utcOffsetStr: "GMT+10:00",
    region: "HST",
    city: "",
    currentTime: "11:06 AM",
  },
  {
    name: "Pacific/Honolulu",
    offset: -600,
    utcOffsetStr: "GMT+10:00",
    region: "Pacific",
    city: "Honolulu",
    currentTime: "11:06 AM",
  },
  {
    name: "Pacific/Johnston",
    offset: -600,
    utcOffsetStr: "GMT+10:00",
    region: "Pacific",
    city: "Johnston",
    currentTime: "11:06 AM",
  },
  {
    name: "Pacific/Rarotonga",
    offset: -600,
    utcOffsetStr: "GMT+10:00",
    region: "Pacific",
    city: "Rarotonga",
    currentTime: "11:06 AM",
  },
  {
    name: "Pacific/Tahiti",
    offset: -600,
    utcOffsetStr: "GMT+10:00",
    region: "Pacific",
    city: "Tahiti",
    currentTime: "11:06 AM",
  },
  {
    name: "Pacific/Marquesas",
    offset: -570,
    utcOffsetStr: "GMT+09:30",
    region: "Pacific",
    city: "Marquesas",
    currentTime: "11:36 AM",
  },
  {
    name: "America/Adak",
    offset: -540,
    utcOffsetStr: "GMT+09:00",
    region: "America",
    city: "Adak",
    currentTime: "12:06 PM",
  },
  {
    name: "America/Atka",
    offset: -540,
    utcOffsetStr: "GMT+09:00",
    region: "America",
    city: "Atka",
    currentTime: "12:06 PM",
  },
  {
    name: "Pacific/Gambier",
    offset: -540,
    utcOffsetStr: "GMT+09:00",
    region: "Pacific",
    city: "Gambier",
    currentTime: "12:06 PM",
  },
  {
    name: "America/Anchorage",
    offset: -480,
    utcOffsetStr: "GMT+08:00",
    region: "America",
    city: "Anchorage",
    currentTime: "1:06 PM",
  },
  {
    name: "America/Juneau",
    offset: -480,
    utcOffsetStr: "GMT+08:00",
    region: "America",
    city: "Juneau",
    currentTime: "1:06 PM",
  },
  {
    name: "America/Metlakatla",
    offset: -480,
    utcOffsetStr: "GMT+08:00",
    region: "America",
    city: "Metlakatla",
    currentTime: "1:06 PM",
  },
  {
    name: "America/Nome",
    offset: -480,
    utcOffsetStr: "GMT+08:00",
    region: "America",
    city: "Nome",
    currentTime: "1:06 PM",
  },
  {
    name: "America/Sitka",
    offset: -480,
    utcOffsetStr: "GMT+08:00",
    region: "America",
    city: "Sitka",
    currentTime: "1:06 PM",
  },
  {
    name: "America/Yakutat",
    offset: -480,
    utcOffsetStr: "GMT+08:00",
    region: "America",
    city: "Yakutat",
    currentTime: "1:06 PM",
  },
  {
    name: "Pacific/Pitcairn",
    offset: -480,
    utcOffsetStr: "GMT+08:00",
    region: "Pacific",
    city: "Pitcairn",
    currentTime: "1:06 PM",
  },
  {
    name: "America/Creston",
    offset: -420,
    utcOffsetStr: "GMT+07:00",
    region: "America",
    city: "Creston",
    currentTime: "2:06 PM",
  },
  {
    name: "America/Dawson",
    offset: -420,
    utcOffsetStr: "GMT+07:00",
    region: "America",
    city: "Dawson",
    currentTime: "2:06 PM",
  },
  {
    name: "America/Dawson_Creek",
    offset: -420,
    utcOffsetStr: "GMT+07:00",
    region: "America",
    city: "Dawson Creek",
    currentTime: "2:06 PM",
  },
  {
    name: "America/Ensenada",
    offset: -420,
    utcOffsetStr: "GMT+07:00",
    region: "America",
    city: "Ensenada",
    currentTime: "2:06 PM",
  },
  {
    name: "America/Fort_Nelson",
    offset: -420,
    utcOffsetStr: "GMT+07:00",
    region: "America",
    city: "Fort Nelson",
    currentTime: "2:06 PM",
  },
  {
    name: "America/Hermosillo",
    offset: -420,
    utcOffsetStr: "GMT+07:00",
    region: "America",
    city: "Hermosillo",
    currentTime: "2:06 PM",
  },
  {
    name: "America/Los_Angeles",
    offset: -420,
    utcOffsetStr: "GMT+07:00",
    region: "America",
    city: "Los Angeles",
    currentTime: "2:06 PM",
  },
  {
    name: "America/Mazatlan",
    offset: -420,
    utcOffsetStr: "GMT+07:00",
    region: "America",
    city: "Mazatlan",
    currentTime: "2:06 PM",
  },
  {
    name: "America/Phoenix",
    offset: -420,
    utcOffsetStr: "GMT+07:00",
    region: "America",
    city: "Phoenix",
    currentTime: "2:06 PM",
  },
  {
    name: "America/Santa_Isabel",
    offset: -420,
    utcOffsetStr: "GMT+07:00",
    region: "America",
    city: "Santa Isabel",
    currentTime: "2:06 PM",
  },
  {
    name: "America/Tijuana",
    offset: -420,
    utcOffsetStr: "GMT+07:00",
    region: "America",
    city: "Tijuana",
    currentTime: "2:06 PM",
  },
  {
    name: "America/Vancouver",
    offset: -420,
    utcOffsetStr: "GMT+07:00",
    region: "America",
    city: "Vancouver",
    currentTime: "2:06 PM",
  },
  {
    name: "America/Whitehorse",
    offset: -420,
    utcOffsetStr: "GMT+07:00",
    region: "America",
    city: "Whitehorse",
    currentTime: "2:06 PM",
  },
  {
    name: "MST",
    offset: -420,
    utcOffsetStr: "GMT+07:00",
    region: "MST",
    city: "",
    currentTime: "2:06 PM",
  },
  {
    name: "PST8PDT",
    offset: -420,
    utcOffsetStr: "GMT+07:00",
    region: "PST8PDT",
    city: "",
    currentTime: "2:06 PM",
  },
  {
    name: "America/Bahia_Banderas",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Bahia Banderas",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Belize",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Belize",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Boise",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Boise",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Cambridge_Bay",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Cambridge Bay",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Chihuahua",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Chihuahua",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Ciudad_Juarez",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Ciudad Juarez",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Costa_Rica",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Costa Rica",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Denver",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Denver",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Edmonton",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Edmonton",
    currentTime: "3:06 PM",
  },
  {
    name: "America/El_Salvador",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "El Salvador",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Guatemala",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Guatemala",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Inuvik",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Inuvik",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Managua",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Managua",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Merida",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Merida",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Mexico_City",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Mexico City",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Monterrey",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Monterrey",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Regina",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Regina",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Shiprock",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Shiprock",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Swift_Current",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Swift Current",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Tegucigalpa",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Tegucigalpa",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Yellowknife",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "America",
    city: "Yellowknife",
    currentTime: "3:06 PM",
  },
  {
    name: "MST7MDT",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "MST7MDT",
    city: "",
    currentTime: "3:06 PM",
  },
  {
    name: "Pacific/Galapagos",
    offset: -360,
    utcOffsetStr: "GMT+06:00",
    region: "Pacific",
    city: "Galapagos",
    currentTime: "3:06 PM",
  },
  {
    name: "America/Atikokan",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Atikokan",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Bogota",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Bogota",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Cancun",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Cancun",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Cayman",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Cayman",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Chicago",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Chicago",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Coral_Harbour",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Coral Harbour",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Eirunepe",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Eirunepe",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Guayaquil",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Guayaquil",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Indiana/Knox",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Indiana/Knox",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Indiana/Tell_City",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Indiana/Tell City",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Jamaica",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Jamaica",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Knox_IN",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Knox IN",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Lima",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Lima",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Matamoros",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Matamoros",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Menominee",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Menominee",
    currentTime: "4:06 PM",
  },
  {
    name: "America/North_Dakota/Beulah",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "North Dakota/Beulah",
    currentTime: "4:06 PM",
  },
  {
    name: "America/North_Dakota/Center",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "North Dakota/Center",
    currentTime: "4:06 PM",
  },
  {
    name: "America/North_Dakota/New_Salem",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "North Dakota/New Salem",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Ojinaga",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Ojinaga",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Panama",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Panama",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Porto_Acre",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Porto Acre",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Rainy_River",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Rainy River",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Rankin_Inlet",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Rankin Inlet",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Resolute",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Resolute",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Rio_Branco",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Rio Branco",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Winnipeg",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "America",
    city: "Winnipeg",
    currentTime: "4:06 PM",
  },
  {
    name: "CST6CDT",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "CST6CDT",
    city: "",
    currentTime: "4:06 PM",
  },
  {
    name: "EST",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "EST",
    city: "",
    currentTime: "4:06 PM",
  },
  {
    name: "Pacific/Easter",
    offset: -300,
    utcOffsetStr: "GMT+05:00",
    region: "Pacific",
    city: "Easter",
    currentTime: "4:06 PM",
  },
  {
    name: "America/Anguilla",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Anguilla",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Antigua",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Antigua",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Aruba",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Aruba",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Barbados",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Barbados",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Blanc-Sablon",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Blanc-Sablon",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Boa_Vista",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Boa Vista",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Campo_Grande",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Campo Grande",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Caracas",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Caracas",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Cuiaba",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Cuiaba",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Curacao",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Curacao",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Detroit",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Detroit",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Dominica",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Dominica",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Fort_Wayne",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Fort Wayne",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Grand_Turk",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Grand Turk",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Grenada",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Grenada",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Guadeloupe",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Guadeloupe",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Guyana",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Guyana",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Havana",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Havana",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Indiana/Indianapolis",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Indiana/Indianapolis",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Indiana/Marengo",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Indiana/Marengo",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Indiana/Petersburg",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Indiana/Petersburg",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Indiana/Vevay",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Indiana/Vevay",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Indiana/Vincennes",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Indiana/Vincennes",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Indiana/Winamac",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Indiana/Winamac",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Indianapolis",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Indianapolis",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Iqaluit",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Iqaluit",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Kentucky/Louisville",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Kentucky/Louisville",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Kentucky/Monticello",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Kentucky/Monticello",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Kralendijk",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Kralendijk",
    currentTime: "5:06 PM",
  },
  {
    name: "America/La_Paz",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "La Paz",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Louisville",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Louisville",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Lower_Princes",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Lower Princes",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Manaus",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Manaus",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Marigot",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Marigot",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Martinique",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Martinique",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Montreal",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Montreal",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Montserrat",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Montserrat",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Nassau",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Nassau",
    currentTime: "5:06 PM",
  },
  {
    name: "America/New_York",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "New York",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Nipigon",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Nipigon",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Pangnirtung",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Pangnirtung",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Port-au-Prince",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Port-au-Prince",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Port_of_Spain",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Port of Spain",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Porto_Velho",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Porto Velho",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Puerto_Rico",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Puerto Rico",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Santo_Domingo",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Santo Domingo",
    currentTime: "5:06 PM",
  },
  {
    name: "America/St_Barthelemy",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "St Barthelemy",
    currentTime: "5:06 PM",
  },
  {
    name: "America/St_Kitts",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "St Kitts",
    currentTime: "5:06 PM",
  },
  {
    name: "America/St_Lucia",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "St Lucia",
    currentTime: "5:06 PM",
  },
  {
    name: "America/St_Thomas",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "St Thomas",
    currentTime: "5:06 PM",
  },
  {
    name: "America/St_Vincent",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "St Vincent",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Thunder_Bay",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Thunder Bay",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Toronto",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Toronto",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Tortola",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Tortola",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Virgin",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "America",
    city: "Virgin",
    currentTime: "5:06 PM",
  },
  {
    name: "EST5EDT",
    offset: -240,
    utcOffsetStr: "GMT+04:00",
    region: "EST5EDT",
    city: "",
    currentTime: "5:06 PM",
  },
  {
    name: "America/Araguaina",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Araguaina",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Argentina/Buenos_Aires",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Argentina/Buenos Aires",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Argentina/Catamarca",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Argentina/Catamarca",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Argentina/ComodRivadavia",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Argentina/ComodRivadavia",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Argentina/Cordoba",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Argentina/Cordoba",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Argentina/Jujuy",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Argentina/Jujuy",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Argentina/La_Rioja",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Argentina/La Rioja",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Argentina/Mendoza",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Argentina/Mendoza",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Argentina/Rio_Gallegos",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Argentina/Rio Gallegos",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Argentina/Salta",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Argentina/Salta",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Argentina/San_Juan",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Argentina/San Juan",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Argentina/San_Luis",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Argentina/San Luis",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Argentina/Tucuman",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Argentina/Tucuman",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Argentina/Ushuaia",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Argentina/Ushuaia",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Asuncion",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Asuncion",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Bahia",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Bahia",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Belem",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Belem",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Buenos_Aires",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Buenos Aires",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Catamarca",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Catamarca",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Cayenne",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Cayenne",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Cordoba",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Cordoba",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Fortaleza",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Fortaleza",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Glace_Bay",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Glace Bay",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Goose_Bay",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Goose Bay",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Halifax",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Halifax",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Jujuy",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Jujuy",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Maceio",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Maceio",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Mendoza",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Mendoza",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Moncton",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Moncton",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Montevideo",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Montevideo",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Paramaribo",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Paramaribo",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Punta_Arenas",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Punta Arenas",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Recife",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Recife",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Rosario",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Rosario",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Santarem",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Santarem",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Santiago",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Santiago",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Sao_Paulo",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Sao Paulo",
    currentTime: "6:06 PM",
  },
  {
    name: "America/Thule",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "America",
    city: "Thule",
    currentTime: "6:06 PM",
  },
  {
    name: "Antarctica/Palmer",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "Antarctica",
    city: "Palmer",
    currentTime: "6:06 PM",
  },
  {
    name: "Antarctica/Rothera",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "Antarctica",
    city: "Rothera",
    currentTime: "6:06 PM",
  },
  {
    name: "Atlantic/Bermuda",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "Atlantic",
    city: "Bermuda",
    currentTime: "6:06 PM",
  },
  {
    name: "Atlantic/Stanley",
    offset: -180,
    utcOffsetStr: "GMT+03:00",
    region: "Atlantic",
    city: "Stanley",
    currentTime: "6:06 PM",
  },
  {
    name: "America/St_Johns",
    offset: -150,
    utcOffsetStr: "GMT+02:30",
    region: "America",
    city: "St Johns",
    currentTime: "6:36 PM",
  },
  {
    name: "America/Miquelon",
    offset: -120,
    utcOffsetStr: "GMT+02:00",
    region: "America",
    city: "Miquelon",
    currentTime: "7:06 PM",
  },
  {
    name: "America/Noronha",
    offset: -120,
    utcOffsetStr: "GMT+02:00",
    region: "America",
    city: "Noronha",
    currentTime: "7:06 PM",
  },
  {
    name: "Atlantic/South_Georgia",
    offset: -120,
    utcOffsetStr: "GMT+02:00",
    region: "Atlantic",
    city: "South Georgia",
    currentTime: "7:06 PM",
  },
  {
    name: "America/Godthab",
    offset: -60,
    utcOffsetStr: "GMT+01:00",
    region: "America",
    city: "Godthab",
    currentTime: "8:06 PM",
  },
  {
    name: "America/Nuuk",
    offset: -60,
    utcOffsetStr: "GMT+01:00",
    region: "America",
    city: "Nuuk",
    currentTime: "8:06 PM",
  },
  {
    name: "America/Scoresbysund",
    offset: -60,
    utcOffsetStr: "GMT+01:00",
    region: "America",
    city: "Scoresbysund",
    currentTime: "8:06 PM",
  },
  {
    name: "Atlantic/Cape_Verde",
    offset: -60,
    utcOffsetStr: "GMT+01:00",
    region: "Atlantic",
    city: "Cape Verde",
    currentTime: "8:06 PM",
  },
  {
    name: "Africa/Abidjan",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Africa",
    city: "Abidjan",
    currentTime: "9:06 PM",
  },
  {
    name: "Africa/Accra",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Africa",
    city: "Accra",
    currentTime: "9:06 PM",
  },
  {
    name: "Africa/Bamako",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Africa",
    city: "Bamako",
    currentTime: "9:06 PM",
  },
  {
    name: "Africa/Banjul",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Africa",
    city: "Banjul",
    currentTime: "9:06 PM",
  },
  {
    name: "Africa/Bissau",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Africa",
    city: "Bissau",
    currentTime: "9:06 PM",
  },
  {
    name: "Africa/Conakry",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Africa",
    city: "Conakry",
    currentTime: "9:06 PM",
  },
  {
    name: "Africa/Dakar",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Africa",
    city: "Dakar",
    currentTime: "9:06 PM",
  },
  {
    name: "Africa/Freetown",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Africa",
    city: "Freetown",
    currentTime: "9:06 PM",
  },
  {
    name: "Africa/Lome",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Africa",
    city: "Lome",
    currentTime: "9:06 PM",
  },
  {
    name: "Africa/Monrovia",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Africa",
    city: "Monrovia",
    currentTime: "9:06 PM",
  },
  {
    name: "Africa/Nouakchott",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Africa",
    city: "Nouakchott",
    currentTime: "9:06 PM",
  },
  {
    name: "Africa/Ouagadougou",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Africa",
    city: "Ouagadougou",
    currentTime: "9:06 PM",
  },
  {
    name: "Africa/Sao_Tome",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Africa",
    city: "Sao Tome",
    currentTime: "9:06 PM",
  },
  {
    name: "Africa/Timbuktu",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Africa",
    city: "Timbuktu",
    currentTime: "9:06 PM",
  },
  {
    name: "America/Danmarkshavn",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "America",
    city: "Danmarkshavn",
    currentTime: "9:06 PM",
  },
  {
    name: "Atlantic/Azores",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Atlantic",
    city: "Azores",
    currentTime: "9:06 PM",
  },
  {
    name: "Atlantic/Reykjavik",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Atlantic",
    city: "Reykjavik",
    currentTime: "9:06 PM",
  },
  {
    name: "Atlantic/St_Helena",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Atlantic",
    city: "St Helena",
    currentTime: "9:06 PM",
  },
  {
    name: "Etc/Greenwich",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Etc",
    city: "Greenwich",
    currentTime: "9:06 PM",
  },
  {
    name: "Etc/UCT",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Etc",
    city: "UCT",
    currentTime: "9:06 PM",
  },
  {
    name: "Etc/UTC",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Etc",
    city: "UTC",
    currentTime: "9:06 PM",
  },
  {
    name: "Etc/Universal",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Etc",
    city: "Universal",
    currentTime: "9:06 PM",
  },
  {
    name: "Etc/Zulu",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "Etc",
    city: "Zulu",
    currentTime: "9:06 PM",
  },
  {
    name: "GMT+0",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "GMT+0",
    city: "",
    currentTime: "9:06 PM",
  },
  {
    name: "GMT-0",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "GMT-0",
    city: "",
    currentTime: "9:06 PM",
  },
  {
    name: "GMT0",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "GMT0",
    city: "",
    currentTime: "9:06 PM",
  },
  {
    name: "UTC",
    offset: 0,
    utcOffsetStr: "GMT+00:00",
    region: "UTC",
    city: "",
    currentTime: "9:06 PM",
  },
  {
    name: "Africa/Algiers",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Africa",
    city: "Algiers",
    currentTime: "10:06 PM",
  },
  {
    name: "Africa/Bangui",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Africa",
    city: "Bangui",
    currentTime: "10:06 PM",
  },
  {
    name: "Africa/Brazzaville",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Africa",
    city: "Brazzaville",
    currentTime: "10:06 PM",
  },
  {
    name: "Africa/Casablanca",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Africa",
    city: "Casablanca",
    currentTime: "10:06 PM",
  },
  {
    name: "Africa/Douala",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Africa",
    city: "Douala",
    currentTime: "10:06 PM",
  },
  {
    name: "Africa/El_Aaiun",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Africa",
    city: "El Aaiun",
    currentTime: "10:06 PM",
  },
  {
    name: "Africa/Kinshasa",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Africa",
    city: "Kinshasa",
    currentTime: "10:06 PM",
  },
  {
    name: "Africa/Lagos",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Africa",
    city: "Lagos",
    currentTime: "10:06 PM",
  },
  {
    name: "Africa/Libreville",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Africa",
    city: "Libreville",
    currentTime: "10:06 PM",
  },
  {
    name: "Africa/Luanda",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Africa",
    city: "Luanda",
    currentTime: "10:06 PM",
  },
  {
    name: "Africa/Malabo",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Africa",
    city: "Malabo",
    currentTime: "10:06 PM",
  },
  {
    name: "Africa/Ndjamena",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Africa",
    city: "Ndjamena",
    currentTime: "10:06 PM",
  },
  {
    name: "Africa/Niamey",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Africa",
    city: "Niamey",
    currentTime: "10:06 PM",
  },
  {
    name: "Africa/Porto-Novo",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Africa",
    city: "Porto-Novo",
    currentTime: "10:06 PM",
  },
  {
    name: "Africa/Tunis",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Africa",
    city: "Tunis",
    currentTime: "10:06 PM",
  },
  {
    name: "Atlantic/Canary",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Atlantic",
    city: "Canary",
    currentTime: "10:06 PM",
  },
  {
    name: "Atlantic/Faeroe",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Atlantic",
    city: "Faeroe",
    currentTime: "10:06 PM",
  },
  {
    name: "Atlantic/Faroe",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Atlantic",
    city: "Faroe",
    currentTime: "10:06 PM",
  },
  {
    name: "Atlantic/Madeira",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Atlantic",
    city: "Madeira",
    currentTime: "10:06 PM",
  },
  {
    name: "Europe/Belfast",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Europe",
    city: "Belfast",
    currentTime: "10:06 PM",
  },
  {
    name: "Europe/Dublin",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Europe",
    city: "Dublin",
    currentTime: "10:06 PM",
  },
  {
    name: "Europe/Guernsey",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Europe",
    city: "Guernsey",
    currentTime: "10:06 PM",
  },
  {
    name: "Europe/Isle_of_Man",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Europe",
    city: "Isle of Man",
    currentTime: "10:06 PM",
  },
  {
    name: "Europe/Jersey",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Europe",
    city: "Jersey",
    currentTime: "10:06 PM",
  },
  {
    name: "Europe/Lisbon",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Europe",
    city: "Lisbon",
    currentTime: "10:06 PM",
  },
  {
    name: "Europe/London",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "Europe",
    city: "London",
    currentTime: "10:06 PM",
  },
  {
    name: "GB-Eire",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "GB-Eire",
    city: "",
    currentTime: "10:06 PM",
  },
  {
    name: "WET",
    offset: 60,
    utcOffsetStr: "GMT-01:00",
    region: "WET",
    city: "",
    currentTime: "10:06 PM",
  },
  {
    name: "Africa/Blantyre",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Africa",
    city: "Blantyre",
    currentTime: "11:06 PM",
  },
  {
    name: "Africa/Bujumbura",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Africa",
    city: "Bujumbura",
    currentTime: "11:06 PM",
  },
  {
    name: "Africa/Ceuta",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Africa",
    city: "Ceuta",
    currentTime: "11:06 PM",
  },
  {
    name: "Africa/Gaborone",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Africa",
    city: "Gaborone",
    currentTime: "11:06 PM",
  },
  {
    name: "Africa/Harare",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Africa",
    city: "Harare",
    currentTime: "11:06 PM",
  },
  {
    name: "Africa/Johannesburg",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Africa",
    city: "Johannesburg",
    currentTime: "11:06 PM",
  },
  {
    name: "Africa/Juba",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Africa",
    city: "Juba",
    currentTime: "11:06 PM",
  },
  {
    name: "Africa/Khartoum",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Africa",
    city: "Khartoum",
    currentTime: "11:06 PM",
  },
  {
    name: "Africa/Kigali",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Africa",
    city: "Kigali",
    currentTime: "11:06 PM",
  },
  {
    name: "Africa/Lubumbashi",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Africa",
    city: "Lubumbashi",
    currentTime: "11:06 PM",
  },
  {
    name: "Africa/Lusaka",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Africa",
    city: "Lusaka",
    currentTime: "11:06 PM",
  },
  {
    name: "Africa/Maputo",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Africa",
    city: "Maputo",
    currentTime: "11:06 PM",
  },
  {
    name: "Africa/Maseru",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Africa",
    city: "Maseru",
    currentTime: "11:06 PM",
  },
  {
    name: "Africa/Mbabane",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Africa",
    city: "Mbabane",
    currentTime: "11:06 PM",
  },
  {
    name: "Africa/Tripoli",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Africa",
    city: "Tripoli",
    currentTime: "11:06 PM",
  },
  {
    name: "Africa/Windhoek",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Africa",
    city: "Windhoek",
    currentTime: "11:06 PM",
  },
  {
    name: "Antarctica/Troll",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Antarctica",
    city: "Troll",
    currentTime: "11:06 PM",
  },
  {
    name: "Arctic/Longyearbyen",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Arctic",
    city: "Longyearbyen",
    currentTime: "11:06 PM",
  },
  {
    name: "Atlantic/Jan_Mayen",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Atlantic",
    city: "Jan Mayen",
    currentTime: "11:06 PM",
  },
  {
    name: "CET",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "CET",
    city: "",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Amsterdam",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Amsterdam",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Andorra",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Andorra",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Belgrade",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Belgrade",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Berlin",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Berlin",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Bratislava",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Bratislava",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Brussels",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Brussels",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Budapest",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Budapest",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Busingen",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Busingen",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Copenhagen",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Copenhagen",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Gibraltar",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Gibraltar",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Kaliningrad",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Kaliningrad",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Ljubljana",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Ljubljana",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Luxembourg",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Luxembourg",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Madrid",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Madrid",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Malta",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Malta",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Monaco",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Monaco",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Oslo",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Oslo",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Paris",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Paris",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Podgorica",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Podgorica",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Prague",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Prague",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Rome",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Rome",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/San_Marino",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "San Marino",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Sarajevo",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Sarajevo",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Skopje",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Skopje",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Stockholm",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Stockholm",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Tirane",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Tirane",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Vaduz",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Vaduz",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Vatican",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Vatican",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Vienna",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Vienna",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Warsaw",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Warsaw",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Zagreb",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Zagreb",
    currentTime: "11:06 PM",
  },
  {
    name: "Europe/Zurich",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "Europe",
    city: "Zurich",
    currentTime: "11:06 PM",
  },
  {
    name: "MET",
    offset: 120,
    utcOffsetStr: "GMT-02:00",
    region: "MET",
    city: "",
    currentTime: "11:06 PM",
  },
  {
    name: "Africa/Addis_Ababa",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Africa",
    city: "Addis Ababa",
    currentTime: "12:06 AM",
  },
  {
    name: "Africa/Asmara",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Africa",
    city: "Asmara",
    currentTime: "12:06 AM",
  },
  {
    name: "Africa/Asmera",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Africa",
    city: "Asmera",
    currentTime: "12:06 AM",
  },
  {
    name: "Africa/Cairo",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Africa",
    city: "Cairo",
    currentTime: "12:06 AM",
  },
  {
    name: "Africa/Dar_es_Salaam",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Africa",
    city: "Dar es Salaam",
    currentTime: "12:06 AM",
  },
  {
    name: "Africa/Djibouti",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Africa",
    city: "Djibouti",
    currentTime: "12:06 AM",
  },
  {
    name: "Africa/Kampala",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Africa",
    city: "Kampala",
    currentTime: "12:06 AM",
  },
  {
    name: "Africa/Mogadishu",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Africa",
    city: "Mogadishu",
    currentTime: "12:06 AM",
  },
  {
    name: "Africa/Nairobi",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Africa",
    city: "Nairobi",
    currentTime: "12:06 AM",
  },
  {
    name: "Antarctica/Syowa",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Antarctica",
    city: "Syowa",
    currentTime: "12:06 AM",
  },
  {
    name: "Asia/Aden",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Asia",
    city: "Aden",
    currentTime: "12:06 AM",
  },
  {
    name: "Asia/Amman",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Asia",
    city: "Amman",
    currentTime: "12:06 AM",
  },
  {
    name: "Asia/Baghdad",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Asia",
    city: "Baghdad",
    currentTime: "12:06 AM",
  },
  {
    name: "Asia/Bahrain",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Asia",
    city: "Bahrain",
    currentTime: "12:06 AM",
  },
  {
    name: "Asia/Beirut",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Asia",
    city: "Beirut",
    currentTime: "12:06 AM",
  },
  {
    name: "Asia/Damascus",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Asia",
    city: "Damascus",
    currentTime: "12:06 AM",
  },
  {
    name: "Asia/Famagusta",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Asia",
    city: "Famagusta",
    currentTime: "12:06 AM",
  },
  {
    name: "Asia/Gaza",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Asia",
    city: "Gaza",
    currentTime: "12:06 AM",
  },
  {
    name: "Asia/Hebron",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Asia",
    city: "Hebron",
    currentTime: "12:06 AM",
  },
  {
    name: "Asia/Istanbul",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Asia",
    city: "Istanbul",
    currentTime: "12:06 AM",
  },
  {
    name: "Asia/Jerusalem",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Asia",
    city: "Jerusalem",
    currentTime: "12:06 AM",
  },
  {
    name: "Asia/Kuwait",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Asia",
    city: "Kuwait",
    currentTime: "12:06 AM",
  },
  {
    name: "Asia/Nicosia",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Asia",
    city: "Nicosia",
    currentTime: "12:06 AM",
  },
  {
    name: "Asia/Qatar",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Asia",
    city: "Qatar",
    currentTime: "12:06 AM",
  },
  {
    name: "Asia/Riyadh",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Asia",
    city: "Riyadh",
    currentTime: "12:06 AM",
  },
  {
    name: "Asia/Tel_Aviv",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Asia",
    city: "Tel Aviv",
    currentTime: "12:06 AM",
  },
  {
    name: "EET",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "EET",
    city: "",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Athens",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Athens",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Bucharest",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Bucharest",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Chisinau",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Chisinau",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Helsinki",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Helsinki",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Istanbul",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Istanbul",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Kiev",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Kiev",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Kirov",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Kirov",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Kyiv",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Kyiv",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Mariehamn",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Mariehamn",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Minsk",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Minsk",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Moscow",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Moscow",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Nicosia",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Nicosia",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Riga",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Riga",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Simferopol",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Simferopol",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Sofia",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Sofia",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Tallinn",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Tallinn",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Tiraspol",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Tiraspol",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Uzhgorod",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Uzhgorod",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Vilnius",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Vilnius",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Volgograd",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Volgograd",
    currentTime: "12:06 AM",
  },
  {
    name: "Europe/Zaporozhye",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Europe",
    city: "Zaporozhye",
    currentTime: "12:06 AM",
  },
  {
    name: "Indian/Antananarivo",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Indian",
    city: "Antananarivo",
    currentTime: "12:06 AM",
  },
  {
    name: "Indian/Comoro",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Indian",
    city: "Comoro",
    currentTime: "12:06 AM",
  },
  {
    name: "Indian/Mayotte",
    offset: 180,
    utcOffsetStr: "GMT-03:00",
    region: "Indian",
    city: "Mayotte",
    currentTime: "12:06 AM",
  },
  {
    name: "Asia/Tehran",
    offset: 210,
    utcOffsetStr: "GMT-03:30",
    region: "Asia",
    city: "Tehran",
    currentTime: "12:36 AM",
  },
  {
    name: "Asia/Baku",
    offset: 240,
    utcOffsetStr: "GMT-04:00",
    region: "Asia",
    city: "Baku",
    currentTime: "1:06 AM",
  },
  {
    name: "Asia/Dubai",
    offset: 240,
    utcOffsetStr: "GMT-04:00",
    region: "Asia",
    city: "Dubai",
    currentTime: "1:06 AM",
  },
  {
    name: "Asia/Muscat",
    offset: 240,
    utcOffsetStr: "GMT-04:00",
    region: "Asia",
    city: "Muscat",
    currentTime: "1:06 AM",
  },
  {
    name: "Asia/Tbilisi",
    offset: 240,
    utcOffsetStr: "GMT-04:00",
    region: "Asia",
    city: "Tbilisi",
    currentTime: "1:06 AM",
  },
  {
    name: "Asia/Yerevan",
    offset: 240,
    utcOffsetStr: "GMT-04:00",
    region: "Asia",
    city: "Yerevan",
    currentTime: "1:06 AM",
  },
  {
    name: "Europe/Astrakhan",
    offset: 240,
    utcOffsetStr: "GMT-04:00",
    region: "Europe",
    city: "Astrakhan",
    currentTime: "1:06 AM",
  },
  {
    name: "Europe/Samara",
    offset: 240,
    utcOffsetStr: "GMT-04:00",
    region: "Europe",
    city: "Samara",
    currentTime: "1:06 AM",
  },
  {
    name: "Europe/Saratov",
    offset: 240,
    utcOffsetStr: "GMT-04:00",
    region: "Europe",
    city: "Saratov",
    currentTime: "1:06 AM",
  },
  {
    name: "Europe/Ulyanovsk",
    offset: 240,
    utcOffsetStr: "GMT-04:00",
    region: "Europe",
    city: "Ulyanovsk",
    currentTime: "1:06 AM",
  },
  {
    name: "Indian/Mahe",
    offset: 240,
    utcOffsetStr: "GMT-04:00",
    region: "Indian",
    city: "Mahe",
    currentTime: "1:06 AM",
  },
  {
    name: "Indian/Mauritius",
    offset: 240,
    utcOffsetStr: "GMT-04:00",
    region: "Indian",
    city: "Mauritius",
    currentTime: "1:06 AM",
  },
  {
    name: "Indian/Reunion",
    offset: 240,
    utcOffsetStr: "GMT-04:00",
    region: "Indian",
    city: "Reunion",
    currentTime: "1:06 AM",
  },
  {
    name: "Asia/Kabul",
    offset: 270,
    utcOffsetStr: "GMT-04:30",
    region: "Asia",
    city: "Kabul",
    currentTime: "1:36 AM",
  },
  {
    name: "Antarctica/Mawson",
    offset: 300,
    utcOffsetStr: "GMT-05:00",
    region: "Antarctica",
    city: "Mawson",
    currentTime: "2:06 AM",
  },
  {
    name: "Antarctica/Vostok",
    offset: 300,
    utcOffsetStr: "GMT-05:00",
    region: "Antarctica",
    city: "Vostok",
    currentTime: "2:06 AM",
  },
  {
    name: "Asia/Almaty",
    offset: 300,
    utcOffsetStr: "GMT-05:00",
    region: "Asia",
    city: "Almaty",
    currentTime: "2:06 AM",
  },
  {
    name: "Asia/Aqtau",
    offset: 300,
    utcOffsetStr: "GMT-05:00",
    region: "Asia",
    city: "Aqtau",
    currentTime: "2:06 AM",
  },
  {
    name: "Asia/Aqtobe",
    offset: 300,
    utcOffsetStr: "GMT-05:00",
    region: "Asia",
    city: "Aqtobe",
    currentTime: "2:06 AM",
  },
  {
    name: "Asia/Ashgabat",
    offset: 300,
    utcOffsetStr: "GMT-05:00",
    region: "Asia",
    city: "Ashgabat",
    currentTime: "2:06 AM",
  },
  {
    name: "Asia/Ashkhabad",
    offset: 300,
    utcOffsetStr: "GMT-05:00",
    region: "Asia",
    city: "Ashkhabad",
    currentTime: "2:06 AM",
  },
  {
    name: "Asia/Atyrau",
    offset: 300,
    utcOffsetStr: "GMT-05:00",
    region: "Asia",
    city: "Atyrau",
    currentTime: "2:06 AM",
  },
  {
    name: "Asia/Dushanbe",
    offset: 300,
    utcOffsetStr: "GMT-05:00",
    region: "Asia",
    city: "Dushanbe",
    currentTime: "2:06 AM",
  },
  {
    name: "Asia/Karachi",
    offset: 300,
    utcOffsetStr: "GMT-05:00",
    region: "Asia",
    city: "Karachi",
    currentTime: "2:06 AM",
  },
  {
    name: "Asia/Oral",
    offset: 300,
    utcOffsetStr: "GMT-05:00",
    region: "Asia",
    city: "Oral",
    currentTime: "2:06 AM",
  },
  {
    name: "Asia/Qostanay",
    offset: 300,
    utcOffsetStr: "GMT-05:00",
    region: "Asia",
    city: "Qostanay",
    currentTime: "2:06 AM",
  },
  {
    name: "Asia/Qyzylorda",
    offset: 300,
    utcOffsetStr: "GMT-05:00",
    region: "Asia",
    city: "Qyzylorda",
    currentTime: "2:06 AM",
  },
  {
    name: "Asia/Samarkand",
    offset: 300,
    utcOffsetStr: "GMT-05:00",
    region: "Asia",
    city: "Samarkand",
    currentTime: "2:06 AM",
  },
  {
    name: "Asia/Tashkent",
    offset: 300,
    utcOffsetStr: "GMT-05:00",
    region: "Asia",
    city: "Tashkent",
    currentTime: "2:06 AM",
  },
  {
    name: "Asia/Yekaterinburg",
    offset: 300,
    utcOffsetStr: "GMT-05:00",
    region: "Asia",
    city: "Yekaterinburg",
    currentTime: "2:06 AM",
  },
  {
    name: "Indian/Kerguelen",
    offset: 300,
    utcOffsetStr: "GMT-05:00",
    region: "Indian",
    city: "Kerguelen",
    currentTime: "2:06 AM",
  },
  {
    name: "Indian/Maldives",
    offset: 300,
    utcOffsetStr: "GMT-05:00",
    region: "Indian",
    city: "Maldives",
    currentTime: "2:06 AM",
  },
  {
    name: "Asia/Calcutta",
    offset: 330,
    utcOffsetStr: "GMT-05:30",
    region: "Asia",
    city: "Calcutta",
    currentTime: "2:36 AM",
  },
  {
    name: "Asia/Colombo",
    offset: 330,
    utcOffsetStr: "GMT-05:30",
    region: "Asia",
    city: "Colombo",
    currentTime: "2:36 AM",
  },
  {
    name: "Asia/Kolkata",
    offset: 330,
    utcOffsetStr: "GMT-05:30",
    region: "Asia",
    city: "Kolkata",
    currentTime: "2:36 AM",
  },
  {
    name: "Asia/Kathmandu",
    offset: 345,
    utcOffsetStr: "GMT-05:45",
    region: "Asia",
    city: "Kathmandu",
    currentTime: "2:51 AM",
  },
  {
    name: "Asia/Katmandu",
    offset: 345,
    utcOffsetStr: "GMT-05:45",
    region: "Asia",
    city: "Katmandu",
    currentTime: "2:51 AM",
  },
  {
    name: "Asia/Bishkek",
    offset: 360,
    utcOffsetStr: "GMT-06:00",
    region: "Asia",
    city: "Bishkek",
    currentTime: "3:06 AM",
  },
  {
    name: "Asia/Dacca",
    offset: 360,
    utcOffsetStr: "GMT-06:00",
    region: "Asia",
    city: "Dacca",
    currentTime: "3:06 AM",
  },
  {
    name: "Asia/Dhaka",
    offset: 360,
    utcOffsetStr: "GMT-06:00",
    region: "Asia",
    city: "Dhaka",
    currentTime: "3:06 AM",
  },
  {
    name: "Asia/Kashgar",
    offset: 360,
    utcOffsetStr: "GMT-06:00",
    region: "Asia",
    city: "Kashgar",
    currentTime: "3:06 AM",
  },
  {
    name: "Asia/Omsk",
    offset: 360,
    utcOffsetStr: "GMT-06:00",
    region: "Asia",
    city: "Omsk",
    currentTime: "3:06 AM",
  },
  {
    name: "Asia/Thimbu",
    offset: 360,
    utcOffsetStr: "GMT-06:00",
    region: "Asia",
    city: "Thimbu",
    currentTime: "3:06 AM",
  },
  {
    name: "Asia/Thimphu",
    offset: 360,
    utcOffsetStr: "GMT-06:00",
    region: "Asia",
    city: "Thimphu",
    currentTime: "3:06 AM",
  },
  {
    name: "Asia/Urumqi",
    offset: 360,
    utcOffsetStr: "GMT-06:00",
    region: "Asia",
    city: "Urumqi",
    currentTime: "3:06 AM",
  },
  {
    name: "Indian/Chagos",
    offset: 360,
    utcOffsetStr: "GMT-06:00",
    region: "Indian",
    city: "Chagos",
    currentTime: "3:06 AM",
  },
  {
    name: "Asia/Rangoon",
    offset: 390,
    utcOffsetStr: "GMT-06:30",
    region: "Asia",
    city: "Rangoon",
    currentTime: "3:36 AM",
  },
  {
    name: "Asia/Yangon",
    offset: 390,
    utcOffsetStr: "GMT-06:30",
    region: "Asia",
    city: "Yangon",
    currentTime: "3:36 AM",
  },
  {
    name: "Indian/Cocos",
    offset: 390,
    utcOffsetStr: "GMT-06:30",
    region: "Indian",
    city: "Cocos",
    currentTime: "3:36 AM",
  },
  {
    name: "Antarctica/Davis",
    offset: 420,
    utcOffsetStr: "GMT-07:00",
    region: "Antarctica",
    city: "Davis",
    currentTime: "4:06 AM",
  },
  {
    name: "Asia/Bangkok",
    offset: 420,
    utcOffsetStr: "GMT-07:00",
    region: "Asia",
    city: "Bangkok",
    currentTime: "4:06 AM",
  },
  {
    name: "Asia/Barnaul",
    offset: 420,
    utcOffsetStr: "GMT-07:00",
    region: "Asia",
    city: "Barnaul",
    currentTime: "4:06 AM",
  },
  {
    name: "Asia/Ho_Chi_Minh",
    offset: 420,
    utcOffsetStr: "GMT-07:00",
    region: "Asia",
    city: "Ho Chi Minh",
    currentTime: "4:06 AM",
  },
  {
    name: "Asia/Hovd",
    offset: 420,
    utcOffsetStr: "GMT-07:00",
    region: "Asia",
    city: "Hovd",
    currentTime: "4:06 AM",
  },
  {
    name: "Asia/Jakarta",
    offset: 420,
    utcOffsetStr: "GMT-07:00",
    region: "Asia",
    city: "Jakarta",
    currentTime: "4:06 AM",
  },
  {
    name: "Asia/Krasnoyarsk",
    offset: 420,
    utcOffsetStr: "GMT-07:00",
    region: "Asia",
    city: "Krasnoyarsk",
    currentTime: "4:06 AM",
  },
  {
    name: "Asia/Novokuznetsk",
    offset: 420,
    utcOffsetStr: "GMT-07:00",
    region: "Asia",
    city: "Novokuznetsk",
    currentTime: "4:06 AM",
  },
  {
    name: "Asia/Novosibirsk",
    offset: 420,
    utcOffsetStr: "GMT-07:00",
    region: "Asia",
    city: "Novosibirsk",
    currentTime: "4:06 AM",
  },
  {
    name: "Asia/Phnom_Penh",
    offset: 420,
    utcOffsetStr: "GMT-07:00",
    region: "Asia",
    city: "Phnom Penh",
    currentTime: "4:06 AM",
  },
  {
    name: "Asia/Pontianak",
    offset: 420,
    utcOffsetStr: "GMT-07:00",
    region: "Asia",
    city: "Pontianak",
    currentTime: "4:06 AM",
  },
  {
    name: "Asia/Saigon",
    offset: 420,
    utcOffsetStr: "GMT-07:00",
    region: "Asia",
    city: "Saigon",
    currentTime: "4:06 AM",
  },
  {
    name: "Asia/Tomsk",
    offset: 420,
    utcOffsetStr: "GMT-07:00",
    region: "Asia",
    city: "Tomsk",
    currentTime: "4:06 AM",
  },
  {
    name: "Asia/Vientiane",
    offset: 420,
    utcOffsetStr: "GMT-07:00",
    region: "Asia",
    city: "Vientiane",
    currentTime: "4:06 AM",
  },
  {
    name: "Indian/Christmas",
    offset: 420,
    utcOffsetStr: "GMT-07:00",
    region: "Indian",
    city: "Christmas",
    currentTime: "4:06 AM",
  },
  {
    name: "Antarctica/Casey",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Antarctica",
    city: "Casey",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Brunei",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Brunei",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Choibalsan",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Choibalsan",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Chongqing",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Chongqing",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Chungking",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Chungking",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Harbin",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Harbin",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Hong_Kong",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Hong Kong",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Irkutsk",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Irkutsk",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Kuala_Lumpur",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Kuala Lumpur",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Kuching",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Kuching",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Macao",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Macao",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Macau",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Macau",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Makassar",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Makassar",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Manila",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Manila",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Shanghai",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Shanghai",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Singapore",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Singapore",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Taipei",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Taipei",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Ujung_Pandang",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Ujung Pandang",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Ulaanbaatar",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Ulaanbaatar",
    currentTime: "5:06 AM",
  },
  {
    name: "Asia/Ulan_Bator",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Asia",
    city: "Ulan Bator",
    currentTime: "5:06 AM",
  },
  {
    name: "Australia/Perth",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Australia",
    city: "Perth",
    currentTime: "5:06 AM",
  },
  {
    name: "Australia/West",
    offset: 480,
    utcOffsetStr: "GMT-08:00",
    region: "Australia",
    city: "West",
    currentTime: "5:06 AM",
  },
  {
    name: "Australia/Eucla",
    offset: 525,
    utcOffsetStr: "GMT-08:45",
    region: "Australia",
    city: "Eucla",
    currentTime: "5:51 AM",
  },
  {
    name: "Asia/Chita",
    offset: 540,
    utcOffsetStr: "GMT-09:00",
    region: "Asia",
    city: "Chita",
    currentTime: "6:06 AM",
  },
  {
    name: "Asia/Dili",
    offset: 540,
    utcOffsetStr: "GMT-09:00",
    region: "Asia",
    city: "Dili",
    currentTime: "6:06 AM",
  },
  {
    name: "Asia/Jayapura",
    offset: 540,
    utcOffsetStr: "GMT-09:00",
    region: "Asia",
    city: "Jayapura",
    currentTime: "6:06 AM",
  },
  {
    name: "Asia/Khandyga",
    offset: 540,
    utcOffsetStr: "GMT-09:00",
    region: "Asia",
    city: "Khandyga",
    currentTime: "6:06 AM",
  },
  {
    name: "Asia/Pyongyang",
    offset: 540,
    utcOffsetStr: "GMT-09:00",
    region: "Asia",
    city: "Pyongyang",
    currentTime: "6:06 AM",
  },
  {
    name: "Asia/Seoul",
    offset: 540,
    utcOffsetStr: "GMT-09:00",
    region: "Asia",
    city: "Seoul",
    currentTime: "6:06 AM",
  },
  {
    name: "Asia/Tokyo",
    offset: 540,
    utcOffsetStr: "GMT-09:00",
    region: "Asia",
    city: "Tokyo",
    currentTime: "6:06 AM",
  },
  {
    name: "Asia/Yakutsk",
    offset: 540,
    utcOffsetStr: "GMT-09:00",
    region: "Asia",
    city: "Yakutsk",
    currentTime: "6:06 AM",
  },
  {
    name: "Pacific/Palau",
    offset: 540,
    utcOffsetStr: "GMT-09:00",
    region: "Pacific",
    city: "Palau",
    currentTime: "6:06 AM",
  },
  {
    name: "Australia/Adelaide",
    offset: 570,
    utcOffsetStr: "GMT-09:30",
    region: "Australia",
    city: "Adelaide",
    currentTime: "6:36 AM",
  },
  {
    name: "Australia/Broken_Hill",
    offset: 570,
    utcOffsetStr: "GMT-09:30",
    region: "Australia",
    city: "Broken Hill",
    currentTime: "6:36 AM",
  },
  {
    name: "Australia/Darwin",
    offset: 570,
    utcOffsetStr: "GMT-09:30",
    region: "Australia",
    city: "Darwin",
    currentTime: "6:36 AM",
  },
  {
    name: "Australia/North",
    offset: 570,
    utcOffsetStr: "GMT-09:30",
    region: "Australia",
    city: "North",
    currentTime: "6:36 AM",
  },
  {
    name: "Australia/South",
    offset: 570,
    utcOffsetStr: "GMT-09:30",
    region: "Australia",
    city: "South",
    currentTime: "6:36 AM",
  },
  {
    name: "Australia/Yancowinna",
    offset: 570,
    utcOffsetStr: "GMT-09:30",
    region: "Australia",
    city: "Yancowinna",
    currentTime: "6:36 AM",
  },
  {
    name: "Antarctica/DumontDUrville",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Antarctica",
    city: "DumontDUrville",
    currentTime: "7:06 AM",
  },
  {
    name: "Antarctica/Macquarie",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Antarctica",
    city: "Macquarie",
    currentTime: "7:06 AM",
  },
  {
    name: "Asia/Ust-Nera",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Asia",
    city: "Ust-Nera",
    currentTime: "7:06 AM",
  },
  {
    name: "Asia/Vladivostok",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Asia",
    city: "Vladivostok",
    currentTime: "7:06 AM",
  },
  {
    name: "Australia/ACT",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Australia",
    city: "ACT",
    currentTime: "7:06 AM",
  },
  {
    name: "Australia/Brisbane",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Australia",
    city: "Brisbane",
    currentTime: "7:06 AM",
  },
  {
    name: "Australia/Canberra",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Australia",
    city: "Canberra",
    currentTime: "7:06 AM",
  },
  {
    name: "Australia/Currie",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Australia",
    city: "Currie",
    currentTime: "7:06 AM",
  },
  {
    name: "Australia/Hobart",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Australia",
    city: "Hobart",
    currentTime: "7:06 AM",
  },
  {
    name: "Australia/Lindeman",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Australia",
    city: "Lindeman",
    currentTime: "7:06 AM",
  },
  {
    name: "Australia/Melbourne",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Australia",
    city: "Melbourne",
    currentTime: "7:06 AM",
  },
  {
    name: "Australia/NSW",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Australia",
    city: "NSW",
    currentTime: "7:06 AM",
  },
  {
    name: "Australia/Queensland",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Australia",
    city: "Queensland",
    currentTime: "7:06 AM",
  },
  {
    name: "Australia/Sydney",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Australia",
    city: "Sydney",
    currentTime: "7:06 AM",
  },
  {
    name: "Australia/Tasmania",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Australia",
    city: "Tasmania",
    currentTime: "7:06 AM",
  },
  {
    name: "Australia/Victoria",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Australia",
    city: "Victoria",
    currentTime: "7:06 AM",
  },
  {
    name: "Pacific/Chuuk",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Pacific",
    city: "Chuuk",
    currentTime: "7:06 AM",
  },
  {
    name: "Pacific/Guam",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Pacific",
    city: "Guam",
    currentTime: "7:06 AM",
  },
  {
    name: "Pacific/Port_Moresby",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Pacific",
    city: "Port Moresby",
    currentTime: "7:06 AM",
  },
  {
    name: "Pacific/Saipan",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Pacific",
    city: "Saipan",
    currentTime: "7:06 AM",
  },
  {
    name: "Pacific/Truk",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Pacific",
    city: "Truk",
    currentTime: "7:06 AM",
  },
  {
    name: "Pacific/Yap",
    offset: 600,
    utcOffsetStr: "GMT-10:00",
    region: "Pacific",
    city: "Yap",
    currentTime: "7:06 AM",
  },
  {
    name: "Australia/LHI",
    offset: 630,
    utcOffsetStr: "GMT-10:30",
    region: "Australia",
    city: "LHI",
    currentTime: "7:36 AM",
  },
  {
    name: "Australia/Lord_Howe",
    offset: 630,
    utcOffsetStr: "GMT-10:30",
    region: "Australia",
    city: "Lord Howe",
    currentTime: "7:36 AM",
  },
  {
    name: "Asia/Magadan",
    offset: 660,
    utcOffsetStr: "GMT-11:00",
    region: "Asia",
    city: "Magadan",
    currentTime: "8:06 AM",
  },
  {
    name: "Asia/Sakhalin",
    offset: 660,
    utcOffsetStr: "GMT-11:00",
    region: "Asia",
    city: "Sakhalin",
    currentTime: "8:06 AM",
  },
  {
    name: "Asia/Srednekolymsk",
    offset: 660,
    utcOffsetStr: "GMT-11:00",
    region: "Asia",
    city: "Srednekolymsk",
    currentTime: "8:06 AM",
  },
  {
    name: "Pacific/Bougainville",
    offset: 660,
    utcOffsetStr: "GMT-11:00",
    region: "Pacific",
    city: "Bougainville",
    currentTime: "8:06 AM",
  },
  {
    name: "Pacific/Efate",
    offset: 660,
    utcOffsetStr: "GMT-11:00",
    region: "Pacific",
    city: "Efate",
    currentTime: "8:06 AM",
  },
  {
    name: "Pacific/Guadalcanal",
    offset: 660,
    utcOffsetStr: "GMT-11:00",
    region: "Pacific",
    city: "Guadalcanal",
    currentTime: "8:06 AM",
  },
  {
    name: "Pacific/Kosrae",
    offset: 660,
    utcOffsetStr: "GMT-11:00",
    region: "Pacific",
    city: "Kosrae",
    currentTime: "8:06 AM",
  },
  {
    name: "Pacific/Norfolk",
    offset: 660,
    utcOffsetStr: "GMT-11:00",
    region: "Pacific",
    city: "Norfolk",
    currentTime: "8:06 AM",
  },
  {
    name: "Pacific/Noumea",
    offset: 660,
    utcOffsetStr: "GMT-11:00",
    region: "Pacific",
    city: "Noumea",
    currentTime: "8:06 AM",
  },
  {
    name: "Pacific/Pohnpei",
    offset: 660,
    utcOffsetStr: "GMT-11:00",
    region: "Pacific",
    city: "Pohnpei",
    currentTime: "8:06 AM",
  },
  {
    name: "Pacific/Ponape",
    offset: 660,
    utcOffsetStr: "GMT-11:00",
    region: "Pacific",
    city: "Ponape",
    currentTime: "8:06 AM",
  },
  {
    name: "Asia/Anadyr",
    offset: 720,
    utcOffsetStr: "GMT-12:00",
    region: "Asia",
    city: "Anadyr",
    currentTime: "9:06 AM",
  },
  {
    name: "Asia/Kamchatka",
    offset: 720,
    utcOffsetStr: "GMT-12:00",
    region: "Asia",
    city: "Kamchatka",
    currentTime: "9:06 AM",
  },
  {
    name: "Pacific/Fiji",
    offset: 720,
    utcOffsetStr: "GMT-12:00",
    region: "Pacific",
    city: "Fiji",
    currentTime: "9:06 AM",
  },
  {
    name: "Pacific/Funafuti",
    offset: 720,
    utcOffsetStr: "GMT-12:00",
    region: "Pacific",
    city: "Funafuti",
    currentTime: "9:06 AM",
  },
  {
    name: "Pacific/Kwajalein",
    offset: 720,
    utcOffsetStr: "GMT-12:00",
    region: "Pacific",
    city: "Kwajalein",
    currentTime: "9:06 AM",
  },
  {
    name: "Pacific/Majuro",
    offset: 720,
    utcOffsetStr: "GMT-12:00",
    region: "Pacific",
    city: "Majuro",
    currentTime: "9:06 AM",
  },
  {
    name: "Pacific/Nauru",
    offset: 720,
    utcOffsetStr: "GMT-12:00",
    region: "Pacific",
    city: "Nauru",
    currentTime: "9:06 AM",
  },
  {
    name: "Pacific/Tarawa",
    offset: 720,
    utcOffsetStr: "GMT-12:00",
    region: "Pacific",
    city: "Tarawa",
    currentTime: "9:06 AM",
  },
  {
    name: "Pacific/Wake",
    offset: 720,
    utcOffsetStr: "GMT-12:00",
    region: "Pacific",
    city: "Wake",
    currentTime: "9:06 AM",
  },
  {
    name: "Pacific/Wallis",
    offset: 720,
    utcOffsetStr: "GMT-12:00",
    region: "Pacific",
    city: "Wallis",
    currentTime: "9:06 AM",
  },
  {
    name: "Antarctica/McMurdo",
    offset: 780,
    utcOffsetStr: "GMT-13:00",
    region: "Antarctica",
    city: "McMurdo",
    currentTime: "10:06 AM",
  },
  {
    name: "Antarctica/South_Pole",
    offset: 780,
    utcOffsetStr: "GMT-13:00",
    region: "Antarctica",
    city: "South Pole",
    currentTime: "10:06 AM",
  },
  {
    name: "Pacific/Apia",
    offset: 780,
    utcOffsetStr: "GMT-13:00",
    region: "Pacific",
    city: "Apia",
    currentTime: "10:06 AM",
  },
  {
    name: "Pacific/Auckland",
    offset: 780,
    utcOffsetStr: "GMT-13:00",
    region: "Pacific",
    city: "Auckland",
    currentTime: "10:06 AM",
  },
  {
    name: "Pacific/Enderbury",
    offset: 780,
    utcOffsetStr: "GMT-13:00",
    region: "Pacific",
    city: "Enderbury",
    currentTime: "10:06 AM",
  },
  {
    name: "Pacific/Fakaofo",
    offset: 780,
    utcOffsetStr: "GMT-13:00",
    region: "Pacific",
    city: "Fakaofo",
    currentTime: "10:06 AM",
  },
  {
    name: "Pacific/Kanton",
    offset: 780,
    utcOffsetStr: "GMT-13:00",
    region: "Pacific",
    city: "Kanton",
    currentTime: "10:06 AM",
  },
  {
    name: "Pacific/Tongatapu",
    offset: 780,
    utcOffsetStr: "GMT-13:00",
    region: "Pacific",
    city: "Tongatapu",
    currentTime: "10:06 AM",
  },
  {
    name: "NZ-CHAT",
    offset: 825,
    utcOffsetStr: "GMT-13:45",
    region: "NZ-CHAT",
    city: "",
    currentTime: "10:51 AM",
  },
  {
    name: "Pacific/Chatham",
    offset: 825,
    utcOffsetStr: "GMT-13:45",
    region: "Pacific",
    city: "Chatham",
    currentTime: "10:51 AM",
  },
  {
    name: "Pacific/Kiritimati",
    offset: 840,
    utcOffsetStr: "GMT-14:00",
    region: "Pacific",
    city: "Kiritimati",
    currentTime: "11:06 AM",
  },
];

export type FilterPeriod =
  | "today"
  | "yesterday"
  | "day"
  | "week"
  | "month"
  | "year"
  | "last24h"
  | "last7d"
  | "last30d"
  | "last12m"
  | "wtd"
  | "mtd"
  | "ytd"
  | "all"
  | "custom";

const period: Record<FilterPeriod, FilterPeriod> = {
  today: "today",
  yesterday: "yesterday",
  day: "day",
  week: "week",
  month: "month",
  year: "year",
  last24h: "last24h",
  last7d: "last7d",
  last30d: "last30d",
  last12m: "last12m",
  wtd: "wtd",
  mtd: "mtd",
  ytd: "ytd",
  all: "all",
  custom: "custom",
};

const periodCalculators = {
  day: (now) => {
    const start = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    return {
      start,
      previousStart: new Date(start.getTime() - 24 * 60 * 60 * 1000),
    };
  },
  last24h: (now) => {
    const start = new Date(now.getTime() - 24 * 60 * 60 * 1000);
    return {
      start,
      previousStart: new Date(start.getTime() - 24 * 60 * 60 * 1000),
    };
  },
  last7d: (now) => {
    const start = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    return {
      start,
      previousStart: new Date(start.getTime() - 7 * 24 * 60 * 60 * 1000),
    };
  },
  last30d: (now) => {
    const start = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    return {
      start,
      previousStart: new Date(start.getTime() - 30 * 24 * 60 * 60 * 1000),
    };
  },
  last12m: (now) => {
    const start = new Date(now.getTime() - 12 * 30 * 24 * 60 * 60 * 1000);
    return {
      start,
      previousStart: new Date(start.getTime() - 12 * 30 * 24 * 60 * 60 * 1000),
    };
  },
  month: (now) => {
    const start = new Date(now.getFullYear(), now.getMonth(), 1);
    return {
      start,
      previousStart: new Date(now.getFullYear(), now.getMonth() - 1, 1),
    };
  },
  mtd: (now) => {
    const start = new Date(now.getFullYear(), now.getMonth(), 1);
    return {
      start,
      previousStart: new Date(now.getFullYear(), now.getMonth() - 1, 1),
    };
  },
  week: (now) => {
    const weekStart = now.getDate() - now.getDay();
    const start = new Date(now.getFullYear(), now.getMonth(), weekStart);
    return {
      start,
      previousStart: new Date(start.getTime() - 7 * 24 * 60 * 60 * 1000),
    };
  },
  wtd: (now) => {
    const wtdStart = now.getDate() - now.getDay();
    const start = new Date(now.getFullYear(), now.getMonth(), wtdStart);
    return {
      start,
      previousStart: new Date(start.getTime() - 7 * 24 * 60 * 60 * 1000),
    };
  },
  year: (now) => {
    const start = new Date(now.getFullYear(), 0, 1);
    return {
      start,
      previousStart: new Date(now.getFullYear() - 1, 0, 1),
    };
  },
  ytd: (now) => {
    const start = new Date(now.getFullYear(), 0, 1);
    return {
      start,
      previousStart: new Date(now.getFullYear() - 1, 0, 1),
    };
  },
  yesterday: (now) => {
    const start = new Date(
      now.getFullYear(),
      now.getMonth(),
      now.getDate() - 1
    );
    return {
      start,
      previousStart: new Date(start.getTime() - 24 * 60 * 60 * 1000),
    };
  },
  today: (now) => {
    const start = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    return {
      start,
      previousStart: new Date(start.getTime() - 24 * 60 * 60 * 1000),
    };
  },
  all: () => {
    const epoch = new Date(0);
    return { start: epoch, previousStart: epoch };
  },
  custom: (now, from, to) => {
    const start = new Date(from);
    return {
      start,
      previousStart: new Date(from.getTime() - (to.getTime() - from.getTime())),
    };
  },
};

function buildDateRange(periodKey, from, to) {
  const now = new Date();
  if (!periodCalculators[periodKey]) {
    throw new Error("Invalid period");
  }
  const { start, previousStart } =
    periodKey === period.custom
      ? periodCalculators[period.custom](now, from, to)
      : periodCalculators[periodKey](now);

  return {
    start: formatDateForClickHouse(start),
    previousStart: formatDateForClickHouse(previousStart),
  };
}

export function addParamToRoutes(routes: any) {
  function extractPattern(route) {
    // Match something like /section/value, return /section/[param]
    const match = route.match(/^\/([^/]+)\/[^/]+$/);
    if (match) {
      return `/${match[1]}/[param]`;
    }
    return null;
  }

  const extended = routes?.map((item) => {
    const url = new URL(item.href);
    const pattern = extractPattern(url.pathname);
    // Compose patternHref as full origin + pattern
    return pattern ? { ...item, patternHref: url.origin + pattern } : item;
  });

  return extended;
}

export { buildDateRange, period };
